### ISSUE TITLE
JavaScript API

### ISSUE THREAD

**Issue by jenius** [jlmakes/scrollreveal.js#1]
Hey Julian,

This project looks great, just curious if you are planning on also including a javascript API for those of us who like to keep html and js separate?

**Comment by iamjosan** [comment]
Passing an object as an argument is a great idea :)

**Comment by jlmakes** [comment]
Hey @iamjosan, got you covered! (#168) :sunglasses: 

I’m working on adding support for passing DOM nodes directly in addition to selectors, and edge cases where you call the API more than once on the same element (for overrides/re-configuration and user error).

Version 3, along with a completely new demo, and revised documentation with examples, will drop this month!

**Comment by joseluisq** [comment]
@jlmakes great !
We await in near future for Docs API.
For now: [Defaults options](https://github.com/jlmakes/scrollReveal.js/blob/master/scrollReveal.js#L58-L88) 

:+1:
