### ISSUE TITLE
CDN version shows as 0.1.2

### ISSUE THREAD

**Issue by donaldallen** [jlmakes/scrollreveal.js#113]
On CloudFlare:
https://cdnjs.com/libraries/scrollreveal.js

And on jsDelivr:
http://www.jsdelivr.com/#!scrollreveal.js

Is this actually `2.1.0`?

**Comment by julianlloyd** [comment]
I’ll post back as soon as I update those resources with `v2.2.0`, Thanks!

**Comment by jlmakes** [comment]
[No more manual pull requests](https://github.com/cdnjs/cdnjs/issues/3638)
[Enabling git(recommended) or npm auto update](https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update)

I’ll be fixing this along with the release of V3.
