### ISSUE TITLE
JS API

### ISSUE THREAD

**Issue by ivansglazunov** [jlmakes/scrollreveal.js#122]
I love to manage these things centrally. Use TypeScript. Is it possible to describe the behavior is not a `data-sr`, such as:

```js
$('.myTag').scrollReveal('wait .5s enter top');
```

I can implement it and make a pull request. Just enter the basic direction in which you would like to add it and can be worth it to make as a separate module wrapper-jquery plugin? How to stop the processing of a particular item?

**Comment by ivansglazunov** [comment]
Perhaps the question is closed, it is possible to do just:

```js
$el.find('.service:nth-child(5)').attr('data-sr', 'wait .1s enter left move 10px');
```

And after all:

```js
window.sr = new scrollReveal({reset: true});
```

However, it would be cool to wrap it in jQuery.fn.
Auto endorses the creation of a separate jQuery plugin?
Example:

```js
$('div').scrollReveal('wait .5s enter top');
$.scrollReveal({ reset: true });
```

**Comment by julianlloyd** [comment]
Hey @ivansglazunov 

JavaScript API and a jQuery plug-in are both great ideas. I’ve got this in the icebox, but I’m not actively working on this yet.

(Duplicate of #1)

**Comment by julianlloyd** [comment]
@ivansglazunov I’m working on a couple other features for `v2.2` so I don’t have plans for this yet, but if you want to work on this with me, that’d be great.

What do you need to get started on a preliminary pull request?
