### ISSUE TITLE
Support for multiple scrollReveal instances

### ISSUE THREAD

**Issue by Unit60** [jlmakes/scrollreveal.js#129]
It would be great to be able to use multiple instances, like for modals, when the DOM of a scrollable area differs...
```JavaScript
window.srBody  = new scrollReveal();
window.srModal = new scrollReveal({
  viewport: document.getElementById( 'defaultModal' )
});
```

**Comment by Unit60** [comment]
Hi Julian
What does 'icebox' mean? I am guessing that this means 'support for multiple instances' is on the shelf for the foreseeable future :(
Still... scrollReveal is a great project... hope it keeps developing!

**Comment by julianlloyd** [comment]
Each new release pulls from the icebox, in addition to whatever bug fixes and features are already on the roadmap.

I’ve been busy studying, working and developing on another project—but don’t worry, adding support for multiple scrollReveal instances is an important feature requests to me, and will see the light of day in the upcoming [2.2](https://github.com/julianlloyd/scrollReveal.js/tree/v2.2.x-WIP) release.
