### ISSUE TITLE
Initializing ScrollReveal after BxSlider loads?

### ISSUE THREAD

**Issue by andresclua** [jlmakes/scrollReveal.js#152]
Hey,
I would like to add effect on BxSlider pager after it is loaded.
```JavaScript
 $('#slider-functional').bxSlider({ controls: false, mode: 'fade' });
 $('.bx-pager').attr( 'data-sr', 'wait 2.9s, enter' );
```
Also, can I add this effect via jQuery?

**Comment by julianlloyd** [comment]
Hey @andresclua 

I’m not familiar with BxSlider, but after taking a look at the BxSlider documentation ([Callback API](http://bxslider.com/examples/callback-api)), I would recommend starting with something like this:

```html
<div class="bx-pager" data-sr="wait 2.9s"> Foo </div>
```
```javascript
var sr, config;

config = { 
  reset: true,
  mobile: true
}

$('.bx-pager').bxSlider({
  onSliderLoad: function(){
    sr = new ScrollReveal( config );
  }
});
```

This code is more or less gibberish, but is meant to point you in the right direction. Hope this helps! :beers:

P.S. In regards to your question:
>"Also, can I add this effect via jQuery?"

I am working hard on v3 of ScrollReveal, sporting a new JavaScript API, revised documentation and new demos. Shhhh! :wink:

**Comment by andresclua** [comment]
Thanks @jlmakes !
