### ISSUE TITLE
Possible Affect on Search Engine Results

### ISSUE THREAD

**Issue by bryanwillis** [jlmakes/scrollReveal.js#153]
I'm not sure if this is an actual issue or not, but google webmaster tools appears to be showing that the scroll reveal is causing the content to not be viewed by its bots. 

I've heard of a couple lazy loading / infinite scrolling plugins having this issue before, but this plugin doesn't seem like it would affect search engine results since the content isn't actually being loaded from ajax or other pages.

 

For example, the webmaster tools reported this is what the bot saw: 

![when using scrollreveal google bot sees this on Dispute Bills](https://lh3.googleusercontent.com/DNzmIHFVeMKmMbpLs37bc-EoJMteLqpwjGi6_gn33sL8=s0 "notworking.jpg")

This is what the pages really looks like below, but the empty spaces above are where I have content loaded by scroll reveal.

![this is what the actual content should be](https://lh3.googleusercontent.com/-Nj5kXDobuXM/VYa0LXPdGEI/AAAAAAAAW9M/PIwMUxpAUrg/s0/work.jpg "work.jpg")

Here is where I'm using the plugin:

[Dispute BIlls](http://disputebills.com)

It's possible I have it loading wrong or the plugin is actually stopping the bot from working, I'm guessing this is just the webmaster preview falsely reporting what it's seeing... Anyway, just thought I'd check.

**Comment by jlmakes** [comment]
Hey @bryanwillis 

scrollReveal.js uses opacity to hide elements, and if you’re using [this tip](https://github.com/jlmakes/scrollReveal.js/wiki/Tips#making-sure-your-elements-load-hidden) (i.e. `[data-sr] { visibility: hidden }`), a visibility property as well.

I don’t think these techniques will impact your SEO: hidden content for UX, especially that doesn’t use `display: none` or weird positioning, [appears to be ok](http://www.tricksbag.com/hidden-text-affects-seo/).

I know it appears to be invisible, but can you confirm the content of your site is indeed indexed by the Google bot?

**Comment by madebylux** [comment]
Hello,

Thanks for your enquiry!

I'm out of the office in various meetings until Wednesday 24th June, so have limited email access.

For urgent web hosting support, please call 0113 3185277, otherwise I will get back to you on my return.

Warm regards,
James

Lux Digital Ltd
e: james@madebylux.com
m: 07734 467977
w: www.madebylux.com
t: 0113 318 5277
a: Tower Works, Globe Road, Leeds LS11 5QG

**Comment by bryanwillis** [comment]
Hey thanks @jlmakes. I had a feeling it was a dumb question to ask, but just wanted to make sure.

Strange thing is now webmaster tools shows that googlebot is seeing the invisible sections... Anyway, thanks again. Great plugin!

**Comment by huevoncito** [comment]
I'd like to reopen this issue because Google is not recognizing my hidden content. The screenshot in the first post by @bryanwillis reflects my situation. Any subsequent thoughts?

**Comment by jlmakes** [comment]
I’m not an SEO expert, but I don‘t see much difference in using JavaScript for tabs, or a "show more" button on a long product description. I understand Google has been working hard on supporting JavaScript, and I wouldn't be surprised if the initial visual state of the page is not necessarily what is indexed.

Is there a way beyond screenshots to see what content is indexed @huevoncito? For what it's worth, all revealed content on [scrollrevealjs.org](https://scrollrevealjs.org) is indexed correctly.

**Comment by huevoncito** [comment]
@jlmakes You're probably right: it must be something else in my page. I'll keep poking away. Probably safe to close this. Thanks for your excellent lib.

**Comment by jlmakes** [comment]
@Aurion72 See above.
