### ISSUE TITLE
Using ScrollReveal with dynamically created objects?

### ISSUE THREAD

**Issue by chamara-fg** [jlmakes/scrollReveal.js#155]
ScrollReveal is not working with dynamically created objects?

**Comment by jlmakes** [comment]
Hi @chamara-fg,

If you created a ScrollReveal instance called `sr` like this:
```js
var sr = new scrollReveal();
```
Calling its `init()` method will re-check the DOM for new elements:
```js
sr.init();
```

Dupe #52 :bee:
