### ISSUE TITLE
Looping animations

### ISSUE THREAD

**Issue by scooterlord** [jlmakes/scrollReveal.js#156]
Hello there (again)! 

You helped before, may help again. I think a cool feature would be for the plugin to include loop animations - how many times it would run, including infinite times.

What do you think? Would this be easy to implement?

**Comment by jlmakes** [comment]
What’s up @scooterlord 

Could you describe a sample use case to help me better understand your idea?

**Comment by scooterlord** [comment]
@jlmakes All cool thanks - considering the confusion in my country these days :S 

Anyway, back on topic! You could use for example this code:

data-sr="enter bottom and move 50px over 0.5s loop 5 times"

data-sr="enter bottom and move 50px over 0.5s loop infinitely"

...This would be extremely useful in cases where you would want an animation to play more than once - think of particles emulation and the such...

**Comment by jlmakes** [comment]
I can imagine particles using looping animations, maybe a looping "floating" animation, but would you really be using ScrollReveal to create those particle animations?

I still don’t see a compelling use case where you would want an element to play its reveal animation repeatedly.

:bee:
