### ISSUE TITLE
Elements not revealing with height: 100%

### ISSUE THREAD

**Issue by queenohearts** [jlmakes/scrollReveal.js#157]
Hey Julian,

Thanks for the great work you've put in this plugin.

I have an issue with the reveal of elements which I've attributed to having body height set to 100% in my CSS. My HTML structure consists of a few sections each with a height set in percentages (let's say each 100%). 

I've made sure the issue is isolated and no 3rd parties are contributing to the problem — you can view my issue here: http://jsfiddle.net/jmquintan/k8amwhut/1/

I have also explored with different ways of setting the section's height as well as their positioning. Originally, each section had `position: relative`, but when I commented out `body { height: 100%; }` and gave sections a specific height in ems, the animations work fine.

It also works when giving the sections a `float: left` and a height in percentages, in addition to commenting out the body height — the thing is I need to have body height set to 100%.  

I would appreciate any insights as to how resolve this. Thanks!

**Comment by queenohearts** [comment]
I have resolved the issue by eliminating the "overflow-x: hidden" attribute. Thought I needed to change something in my config, but nope. I still don't know why hiding overflow-x would cause this, but now it's working for me. If anybody knows why, it would be great to know. Thanks again.

**Comment by jlmakes** [comment]
Thanks for the kind words @queenohearts, and I’m glad you got it working.

It’s a lot to take in at once. Not sure if this is a ScrollReveal bug, a browser oddity or what, but I’ll give it a second look tomorrow.

:beers:
