### ISSUE TITLE
Rotate?

### ISSUE THREAD

**Issue by RonR-WebDesign** [jlmakes/scrollReveal.js#158]
I don't see rotate in keywords.  Is that possible?

**Comment by Honza-B** [comment]
Yes, roll makes element rotate.

**Comment by RonR-WebDesign** [comment]
Ah… now I see it.  Thanks.  

 

Great script, thanks for your efforts!

 

One last question, any way to get it to stop at a set angle.  Example: I’d like and image to roll starting from -90deg and stop at +15deg.

**Comment by Honza-B** [comment]
Well, I'm not sure. But you can try set in css in transform 15deg for element a then roll it by 105deg or -105deg, not sure in sides :-)

**Comment by RonR-WebDesign** [comment]
Yep, tried that.  The css transform is set first and then gets reset by sR.  I’m going to make it easier and simply rotate the image first in Photoshop.

 

Thanks.
