### ISSUE TITLE
Trigger animations based on parent el

### ISSUE THREAD

**Issue by thiagocoelho** [jlmakes/scrollReveal.js#160]
Hello :)

I'm wondering if there is any option to trigger animations based on parent element factor. I'm working on a landing page where there are informations that should be visible when the parent element is already visible.

```html
<div class="parent" data-sr="vFactor 0.6">
  <p class="my-cool-element" data-sr="move 24px">This p should animate based on the parent factor</p>
</div>
```

**Comment by jlmakes** [comment]
Hey @thiagocoelho 

You could use the complete function of the parent element to add the `data-sr` attribute to it’s child, and then re-initialize ScrollReveal with `init()`. You wouldn’t be able to use the `reset` keyword on the parent though, since complete would never fire.

_Pseudo Code Example:_
```js
var config = {
  vFactor: 0.6,
  complete: animateChild
}

window.sr = new scrollReveal( config );

function animateChild( domEl ){
  if ( domEl.classList.contains('parent') ){
    var child; 
    child = domEl.querySelector('.my-cool-element');
    child.setAttribute( 'data-sr', 'move 24px' );
    sr.init();
  }
}
```
#### There’s a problem here though

Having to check the DOM each time an animation completes, when we only need this logic for one element, makes this solution a little rough. Unfortunately, ScrollReveal v2.x shares defaults across all elements, and there is no way to pass a complete function to the `data-sr` string… so there’s not much we can do.

Enter ScrollReveal 3.

SR3 biggest change is a new JavaScript API, which yes means cleaner markup, but you can vary configuration across _n_ element groups. Here’s an example:

_v3.0-RC Code Example:_
```js
var parentConfig
  , defaults;

parentConfig = {
  vFactor: 0.6,
  complete: animateChild
}

defaults = {
  vFactor: 0.15,
  over: 0.5s
}

window.sr = new scrollReveal( defaults );
sr.reveal( '.parent', parentConfig )
sr.init();

function animateChild( domEl ){
  var child = domEl.querySelector('.my-cool-element');
  sr.reveal( child, 'move 24px' ).init();
}
```
ScrollReveal 3 is set to launch July 22nd.

**Comment by thiagocoelho** [comment]
Wow @jlmakes thanks for the answer!

I forgot the `complete` callback, this will work if I don't use reset in the sections.

I talked to my partner and we agree that visually it's more cool maintaining the reset when the user scroll between sections.

But I'm pretty sure that when ScrollReveal 3 is released I will use it!

Nice project you have here by the way :ok_hand:

**Comment by jlmakes** [comment]
Thanks @thiagocoelho 

That’s true, using `reset` removes the ability to use the `complete` callback.

The `reset` keyword was a highly requested feature, and I’ve been wondering if `complete` falls short— and whether it would be a good idea to add more callbacks.

I’m just spit balling here, but maybe something like:
- `config.complete` — Fires when a non-resetting element completes animation.
- `config.afterReveal` — Fires when a resetting element completes a reveal animation.
- `config.afterReset` — Fires when a resetting element completes a reset animation.

However, in this reality, maybe I don’t even need to distinguish between resetting and non-resetting elements. Maybe I don’t even need a `complete` callback…
- `config.afterReveal` — Fires when an element completes a reveal animation.
- `config.afterReset` — Fires when an element completes a reset animation.

What do you think? This would be a breaking change, so I could see this sneaking into SR3 before :rocket:

**Comment by thiagocoelho** [comment]
@jlmakes 

I think that `config.afterReveal` and `config.afterReset` are just fine. I don't see any reason to maintain a `complete` callback, once the `afterReveal` can be the `complete` right?

Just to know if I get the things right. Both callbacks will return the `parent` element as a param?

Something like:

```
<div class="parent">
  <p class="my-cool-element">This p should animate based on the parent factor</p>
</div>
```

```
var config = {
  vFactor:  0.6,
  afterReveal: animateChild,
  afterReset: animateChild
}
```

```
window.sr = new scrollReveal( config );

function animateChild( domEl ){
  var child = domEl.querySelector('.my-cool-element');
 // Do any cool stuff here using child elements or even any other actions
}
```

Maybe a complete callback is not necessary but what do you think about `before` callbacks? Tough that if we have `after`, maybe someone wants to take some action `before` **reveal/reset** (change the background color or anything related).

Please tell me if I'm being nosence here haha :smile:

**Comment by jlmakes** [comment]
Yep, the `complete` callback is passed the DOM node of the element that just finished its animation, so the way you have it there… you could call it the parent element; the `afterReveal` and `afterReset` would likely be the same.

I think `beforeReveal` and `beforeReset` could work, but that would be a new feature—not a breaking change. I’ll hold off on something like that for now.

I think I’m going to explore creating the `after` callbacks. Thanks for the feedback @thiagocoelho
