### ISSUE TITLE
Animation doesn't wait for scroll but complete on load.

### ISSUE THREAD

**Issue by prakarangs** [jlmakes/scrollReveal.js#162]
Hi,
I have this issue when i try to add new section to my website. I apply the same config and `data-sr="enter bottom"` just like i did but the animation is set complete when i scroll down to the end of my old section.

````html
<div class="old-section">
 // Some content
 // with other data-sr="enter bottom" etc.
</div>

// New section here
<div class="shape-section">
  <div class="topic-bkg" data-sr="enter bottom" data-sr-id="85" style="visibility: visible; " data-sr-complete="true"></div>
  <span class="topic-content" data-sr="enter bottom wait 0.2s" data-sr-id="86" style="visibility: visible; " data-sr-complete="true">
    <p>Lorem Ipsum</p>
  </span>
</div>
````

I also set `vFactor: 0.6` in my config and viewport is the document. However, the animation is set `data-sr-complete="true"` at start. 

Did I miss something here? How do I get this working?

**Comment by jlmakes** [comment]
Hi @prakarangs, ScrollReveal no longer uses `data-sr-complete` as of `v2.0.3`.

First things first, I would upgrade to the latest version of ScrollReveal: `v2.3.2`

**Comment by prakarangs** [comment]
@jlmakes It does solve my problem. Thank you. You are the best!
