### ISSUE TITLE
Problem on scrool

### ISSUE THREAD

**Issue by jabiertxof** [jlmakes/scrollReveal.js#163]
Hi,

I have an old JS working, but with the new syntax of `data-sr`, the element has no animation.

Using the old syntax on the new release, it works, like `data-sr="wait 2s and then ease-in-out 150px"` but using like in current GitHub doc couldn't fire animation on scroll. (Sorry I don’t speak english.)

**Comment by jlmakes** [comment]
Sorry @jabiertxof, I don’t quite follow.

Can you provide code examples? There’s definitely a lot that’s changed in ScrollReveal over the past 2 years, so make sure to use the latest version and I can help you get it working.

**Comment by jabiertxof** [comment]
Here is the -simplified- code dont work on iceweasel/firefox 31.8
The js is get from github today.
```
<html>
    <head>
        <meta charset="UTF-8" />
        <script type="text/javascript" src="js/scrollReveal.min.js"></script>
        <style> [data-sr] { visibility: hidden; } </style>
    </head>
    <body>
        <div style="height:2222px"></div>
        <div>
            <div>
                <div data-sr> Foo </div>
                <div data-sr> Bar </div>
                <div data-sr> Baz </div>
                <div data-sr> Bun </div>
            </div>
        </div>
        <div style="height:2222px"></div>
        <script type="text/javascript">
          window.sr = new scrollReveal();
        </script>
    </body>
</html>
```

**Comment by jabiertxof** [comment]
More simplified. No work.
```
<html>
    <head>
        <meta charset="UTF-8" />
        <script type="text/javascript" src="js/scrollReveal.min.js"></script>
        <style> [data-sr] { visibility: hidden; } </style>
    </head>
    <body>
        <div style="height:2222px"></div>
        <div>
            <div data-sr> Foo </div>
            <div data-sr> Bar </div>
            <div data-sr> Baz </div>
            <div data-sr> Bun </div>
        </div>
        <div style="height:2222px"></div>
        <script type="text/javascript">
          window.sr = new scrollReveal();
        </script>
    </body>
</html>
```

**Comment by jabiertxof** [comment]
I lost coment im working localy and also try to put js call script at bottom.

**Comment by thiagocoelho** [comment]
@jabiertxof Let's get things straight. 

1 - Are you using the last version of scrollReveal following the implementation guide?
2 - Have you checked if there is any javascript error on console?
3 - Just in case, try to implement those properties to your **html, body** tags: 

```

**Comment by jabiertxof** [comment]
1 and 2 are ok. 3 fix the problem, 
Thanks so much for the help! :)
