### ISSUE TITLE
Not working on tablets and phones.

### ISSUE THREAD

**Issue by nikola1970** [jlmakes/scrollReveal.js#165]
Is there any way to make this work on tablets and phones? Everything works awesome on my PC but nothing happens on my tablets and phone.

**Comment by nikola1970** [comment]
Found a soulution, it was disabled for mobile devices by default, just added:

window.sr = new scrollReveal({
		mobile: true
	});

and it is workling. Awesome plugin man, love it so much! Thanks!

**Comment by jlmakes** [comment]
Thanks @nikola1970 

:+1: 

I’m actually going to enable that by default in v3.

**Comment by nikola1970** [comment]
That would be logical to be set true by default. You are welcome :)
