### ISSUE TITLE
Problems animating multiple elements with Safari

### ISSUE THREAD

**Issue by chrisxwan** [jlmakes/scrollReveal.js#166]
I'm currently using ScrollReveal to make a bunch of tiny pixelated boxes do random things when scrolled upon, with the following code:

```js
var index=0;
$(document).ready(function(){
	jQuery('.pixel-box').each(function() { //each tiny box has class pixel-box
		var directions =[ 'left', 'right', 'top', 'bottom']

		index += 1

	    var currentElement = $(this);
	    var randEffect = getRandomInt(0,1);
	    var randTime = getRandomArbitrary(1, 3.5);
	    var randDirection = getRandomInt(0,3);

	    if(randEffect == 0){
		    var rand = getRandomInt(-360, 360);
		    $(this).attr('data-sr', 'wait .5s, enter ' + directions[randDirection] + ', flip ' + rand + 'deg, over '+ randTime +'s');
		}
		else if(randEffect == 1){
			// move 24px
			 var rand = getRandomInt(10, 120);
			$(this).attr('data-sr', 'wait .5s, enter ' + directions[randDirection] +', move '+ rand + 'px, over '+ randTime +'s');
		}


	    if(index == 81){
	    	 window.sr = new scrollReveal();
	    }
	});
});
```

It's working perfectly on Chrome, but on Safari, the behavior is extremely clunky and not what I want. Would you or anyone else have any insights as to why this is happening?

Thanks!

**Comment by chrisxwan** [comment]
To illustrate, here's what it looks like on Chrome:

https://gyazo.com/4f51ff8279cf5a76ad3ab38a680ae2af

Here's what it looks like on Safari:

https://gyazo.com/8c30e489a2470ac415da3dde1d95d4ef

Thanks!

**Comment by jlmakes** [comment]
Your project looks cool, sorry I’m not of much help on this one. If you send me a link to a live site, I’ll load it up in Safari and take a look.

Sidebar: I’ve thought about supporting ranges for config values for some time now—maybe something like `enter 3..10s over 0.5..2s`? It looks like you’re rolling something similar here already.

**Comment by frankjwu** [comment]
@jlmakes @chrisxwan Looks like an open bug (see: https://code.google.com/p/chromium/issues/detail?id=319407) when animating two CSS properties simultaneously. It looks like it's since been fixed in Chrome, but not yet in Safari.

[This article](https://www.theparticlelab.com/safari-svg-animation-bug/) suggests two fixes, neither of which seem compatible with the way scrollReveal.js currently works, so you might have to rebuild the animation yourself.

**Comment by jlmakes** [comment]
Thanks for that @frankjwu !
