### ISSUE TITLE
Works incorrectly without doctype.

### ISSUE THREAD

**Issue by OEvgeny** [jlmakes/scrollReveal.js#169]
So, I'm not sure it's an issue or not, but think it can save someone a few hours of time :smile:
For some reason I can't get it to work properly without doctype specified.
This works as expected:
```
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
div data-sr>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div
....
<script type="text/javascript" src="https://rawgit.com/jlmakes/scrollReveal.js/master/dist/scrollReveal.js"></script>
<script>
  reset: true,
  move: '50px',
  mobile: true
});
</script>
</body>
</html>
```
But this will work only on scroll to top:
```
<html lang="en">
<head></head>
<body>
div data-sr>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div
....
<script type="text/javascript" src="https://rawgit.com/jlmakes/scrollReveal.js/master/dist/scrollReveal.js"></script>
<script>
  reset: true,
  move: '50px',
  mobile: true
});
</script>
</body>
</html>
```
I'm using ``"scrollreveal": "^2.3.2"`` via npm.
Sorry for my bad English, and thanks.
Good work! Looking forward to 3.0 release.

**Comment by jlmakes** [comment]
Hi @OEvgeny 

I did a quick test, and removing doctype did not break anything on my end. That said, _providing a doctype is always a good idea_, to make sure the browser knows what type of markup you’re using.

Also, the code you provided looks a little broken though—not sure if that’s because of copy paste or what, but maybe try these changes (it should still work even without a doctype):
```html
<html lang="en">
  <body>
    <div data-sr>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </div>
    <script type="text/javascript" src="https://rawgit.com/jlmakes/scrollReveal.js/master/dist/scrollReveal.js"></script>
    <script>
      window sr = new scrollReveal({
        reset: true,
        move:  '50px',
        mobile: true
      });
    </script>
  </body>
</html>
```

**Comment by OEvgeny** [comment]
Thanks for clarification. Unfortunately I can't create a fiddle or something like this, because all of services I know add doctype automatically. And JSBin is not an exception. You can verify this by looking into devtools.

**Comment by jlmakes** [comment]
@OEvgeny Hmm, that may indeed be the case.

For what it’s worth, I also temporarily removed the doctype on http://scrollrevealjs.org to test this, and it still worked as expected.

**Comment by OEvgeny** [comment]
Thanks, I checked JSBin again and you are right. 

Sorry for wasting your time, I was sure that this about doctype. I will test it thoroughly soon.

I'm not avoiding declaring a doctype. I also think that providing a doctype is a good practice. It was my mistake. So, I just thought it will save someone some time.

**Comment by OEvgeny** [comment]
So, this is reproduction on JSBin: http://jsbin.com/weviyihize/edit?html,output
Try to scroll down and than scroll up. For me scroll up works well but scroll down shows all content without any animation.

**Comment by jlmakes** [comment]
Thanks for the demo @OEvgeny! You’re right, its broken without `<!doctype html>`.

I thought you were only using one element to test, but I see the problem is when scrolling multiple elements. (I now understand what the `....` means in your first code examples, haha.)

I wouldn’t call this a bug, but definitely an important tip. I’ve update the [Wiki Tips Section](https://github.com/jlmakes/scrollReveal.js/wiki/Tips)

:beers:

**Comment by OEvgeny** [comment]
Yes, it's a good idea to add it to wiki! Thanks too!
