### ISSUE TITLE
'reset' not working with 'wait'

### ISSUE THREAD

**Issue by nikola1970** [jlmakes/scrollReveal.js#171]
Hello, i just found out that using 'wait' will work only the first time when you reveal it, and if you want to use 'reset' with it, it is not waiting anymore. :/

**Comment by nikola1970** [comment]
Oh, i found out it configration that i have to set delay to "always"! :)

**Comment by jlmakes** [comment]
Hey @nikola1970 

Glad you figured it out. Do you think `always` is a more intuitive default?

**Comment by nikola1970** [comment]
Yep, i do man. Also, "mobile" should be set to true by default too, for responsive. I have to say that ScrollReveal is the best plugin i used so far! Thank you for making it to be so awesome! :)

**Comment by jlmakes** [comment]
I really appreciate the kind words @nikola1970, and I’ll make sure those will be the defaults in ScrollReveal 3!

:beers:

**Comment by nikola1970** [comment]
Cool! Thanks! :+1: :)
