### ISSUE TITLE
Support for media-queries-like options setting

### ISSUE THREAD

**Issue by pawlikdoc** [jlmakes/scrollReveal.js#172]
Hello!

Do you think it is necessary/possible to implement width-dependent configuration?

For example, I have layout grid with 2 columns for wide screens and I set each even list item some delay to make left element in a row appear first and right element in a row appear next. However, my layout changes to 1 column, and there becomes no need to delay even items in my list.

Another words, it would be great to change behaviour
`data-sr='enter left, move 24px, scale up 0%, delay 0.3s'`
into
`data-sr='enter left, move 24px, scale up 0%'`
dynamically on page resize.

**Comment by jlmakes** [comment]
I think that makes perfect sense, especially with the use case you described: using delay only under certain conditions. I’m going to keep this in mind for future releases.

As far as achieving this right now in your current project, you’ve caught me at an odd time. You’re probably using v2.3, but the heavily refactored Scroll Reveal 3 drops soon… and it's primary feature is the new [JavaScript API](https://github.com/jlmakes/scrollReveal.js/pull/168).

It's this API that I think will allow for something like this:
- detect width (let's say 1000px)
- configure elements (config with delay)
- add listener for width changes
- initialize ScrollReveal
- on width change (let's say now 400px)
- re-configure elements (config without delay)
- initialize ScrollReveal

Now, I would say just grab the release candidate and start experimenting, but—this is why I say you’ve caught me an odd time—the current release candidate still has bugs when the same element is configured more than once. This is literally what I am in the middle of fixing in my development branch.

#### So...

This should be possible with an event handler bound to the window resize event, that checks the current width and uses the new JS API to set the appropriate configuration.

I just need a little more time to work on V3.

**Comment by jlmakes** [comment]
Hey @pawlikdoc, the latest release candidate now properly supports multiple `reveal()` calls on the same element set.

Are you still interested in getting this working?

**Comment by pawlikdoc** [comment]
Ok thanks. I don't know if i will use it in the future, great improvement though.
