### ISSUE TITLE
Sticky after Reveal?

### ISSUE THREAD

**Issue by jarth3000** [jlmakes/scrollReveal.js#173]
Is there a way to stick an element into a fixed position after reveal?

I've tried using StickyJS to pin an element after it's brought into the frame, but using any other function seems to break ScrollReveal. I'm assuming I should use a callback, but when I tried that it broke it as well.

Any ideas guys?

**Comment by jarth3000** [comment]
And by stick an element I mean reveal it and once it hits the top of the page, stick it.

**Comment by jlmakes** [comment]
Hey @jarth3000,

I don’t think you’ll need another third-party library, changing the CSS of an element based on scroll position only requires a few lines of code, something kind of like this:
```css
.fixed {
  position: fixed; !important
}
```
```js
var elem = document.querySelector('#myElem')

window.addEventListener( 'scroll', _handler, false );

  function _handler(){
    if ( window.pageYOffset >= elem.offsetTop ){
      return elem.classList.add('fixed')
    }

    if ( crown.classList.contains('fixed') ){
      return elem.classList.remove('fixed');
    }
  }
```
But, I can’t gaurantee this works with version 2.3 or the upcoming 3.0 yet. Let me look into this, and get back to you!

**Comment by jlmakes** [comment]
Hey @jarth3000,

In my tests, there’s nothing wrong with applying `position: fixed` to an element, and I don’t think you need a third-party library for this—changing the CSS of an element based on scroll position only requires a few lines of code, something kind of like this:

*Sample CSS*
```css
.fixed {
  position: fixed; !important
}
```
*Sample JS*
```js
var myElem = document.querySelector('#myElem')

window.addEventListener( 'scroll', _affixHandler( myElem ), false );

function _affixHandler( elem ){
  if ( window.pageYOffset >= elem.offsetTop ){
    return elem.classList.add('fixed')
  }
}
```
You would want to debounce the event handler (so it doesn’t fire *every single scroll event*, but instead maybe [every ~16ms](http://www.html5rocks.com/en/tutorials/speed/rendering/) or more) and if you want to get fancy, remove the element from ScrollReveal's element store once it's been affixed.

Is this helpful?

**Comment by jlmakes** [comment]
Did you have any luck with this?

Otherwise, I’ll see if I can put together a demo using Version 3, and the updated callbacks…

:bee:

**Comment by jarth3000** [comment]
Sorry, yes. I got it working! Much appreciated.

**Comment by jlmakes** [comment]
Awesome! :beers:

**Comment by shashankbalaji** [comment]
@jarth3000 @jlmakes 
I am new to JS programmimng. Can you give me pointers on how I can do calbacks to pin an html element after animating it during scrolling? A link to a example/demo would be very useful :)

**Comment by jlmakes** [comment]
@shashankbalaji http://jsbin.com/ladutil/edit?html,css,output

This is a simple demonstration using ScrollReveal callbacks and JavaScript to change an elements styles after a reveal animation. :bow:

**Comment by shashankbalaji** [comment]
thanks @jlmakes !
