### ISSUE TITLE
Revealing only when scrolling up

### ISSUE THREAD

**Issue by raftelti** [jlmakes/scrollReveal.js#175]
For some reason, the reveal effect only happens when I am scrolling up, am I doing something wrong or it's some issue with the last build?

Check this: http://raftelti.me/dest/

**Comment by jlmakes** [comment]
Hey @raftelti, see [this comment](https://github.com/jlmakes/scrollReveal.js/issues/111#issuecomment-71376102), in my tests, your demo was fixed by applying:
```css
html, body {
  height: 100%;
}
```

**Comment by raftelti** [comment]
Thanks!
