### ISSUE TITLE
gulp compilation with use strict requiring upper case constructor name

### ISSUE THREAD

**Issue by MarkAddison** [jlmakes/scrollreveal.js#176]
I hit an issue when trying to build an angular application using scrollReveal.js.

The following line cause a compilation error:
```window.sr = new scrollReveal();```

Although it might conceptually seem possible to use the JSHint directive in .jshintrc
`"newcap": true`

With strict it's not possible. Would you be able to alter the definition to ScrollReveal?

Best regards,

Mark

**Comment by jlmakes** [comment]
Hey @MarkAddison 

I don’t see why not, it makes more sense to me as a constructor function to capitalize anyway. I’ll make this change in the imminent v3 release.

Thanks!

**Comment by MarkAddison** [comment]
Hi Julian,

Thanks for the quick response.
Obviously, the change will not be backwards compatible,
but I am certain it will not be too taxing for developers to fix!

Best regards,

Mark

**Comment by jlmakes** [comment]
There are a number of breaking changes in the new 3.0 — you have great timing bringing this up now, so no worries. I’ll just make sure to add another note to the migration guide.

:beers:

**Comment by vburlak** [comment]
+1 have the same issue.
Will be great to see improvement in feature release.
Cheers!

**Comment by jlmakes** [comment]
Hey @vburlak @MarkAddison, getting closer! :beers:
