### ISSUE TITLE
Hide elements while scrolling up

### ISSUE THREAD

**Issue by medvjedusina** [jlmakes/scrollReveal.js#177]
Hi Julian!

Awesome plugin, very easy to work and really does the magic well :) I do have a questions tough.

I have set up everything, and when i scroll down elements are animated properly.
But i was wondering is it possible to revert the animations when i scroll up, aka, to hide them if user scrolls up?

Thank you a bunch!

**Comment by medvjedusina** [comment]
Argh, my bad, i found a way, thanks :)

**Comment by jlmakes** [comment]
Hey no worries @medvjedusina, thanks for using ScrollReveal.

If you have get any ideas on how I can make first-time use easier, please let me know. :bow:
