### ISSUE TITLE
Keep elements shown scrolling back up

### ISSUE THREAD

**Issue by gab1982** [jlmakes/scrollReveal.js#178]
Hi, great plugin :) I like how the elements fade in as a user scrolls down the page but is there a way that I can keep the elements visible as I scroll back up the page so they don't fade out?

thanks

**Comment by Floriangomis** [comment]
You should ask to the guy on this topic seems he found a way ;-) 
https://github.com/jlmakes/scrollReveal.js/issues/177

**Comment by Floriangomis** [comment]
I didn't try but it seems that this should answer to your question nop ? 

https://github.com/jlmakes/scrollReveal.js/wiki/Keywords#reset

**Comment by gab1982** [comment]
Thanks for your reply, I currently have data-sr="enter center wait 0.5s" so by making it: data-sr="enter center wait 0.5s, reset" that doesn't seem to make any difference, perhaps I am doing something wrong as it still fades the element out once going past the viewport.

**Comment by Floriangomis** [comment]
You should try : no reset

reset is doing exactly what you doesn't want :)

**Comment by gab1982** [comment]
Thanks but i tried both of them but neither works

**Comment by jlmakes** [comment]
Thanks @Floriangomis @gab1982

If you have `data-sr` = `reset` it will **force enable** create the element fade you describe when going past the viewport. However, with `no` before, it will **force disable** it. e.g. `data-sr` = `no reset`. In your example, you hadn’t included the `no` keyword.

However, I’m not sure I ever released ScrollReveal with `reset: true` in the default configuration—certainly not the latest v2.3.2 and v.3.0.0-RC.

So even though I recommended ensuring use of `no` keyword in your case, I would also suggest taking a second look at your configuration.

**Comment by gab1982** [comment]
Great thanks the no reset worked, It didn't work before as I had opacity: 0 in my css for that attribute, which I have now removed.

**Comment by Floriangomis** [comment]
Nice to hear :) Have fun !

**Comment by jlmakes** [comment]
Glad it’s working.

@gab1982 I should mention that `enter center` won't actually do anything. If you don’t want any translation, you can use `move 0px` instead.

:beers:
