### ISSUE TITLE
Reveal with reset, but only when scrolling down?

### ISSUE THREAD

**Issue by JanSchmidhofer** [jlmakes/scrollReveal.js#179]
Ist there a possibility to run reveal every time on scrolling down and not on scrolling up ?

**Comment by jlmakes** [comment]
Hey @JanSchmidhofer 

I believe this is possible, but you’ll need to edit the source. Fret not, it’s just a one line change!

Assuming you are running the latest master (v2.3.2), you can take a look at [Line 169](https://github.com/jlmakes/scrollReveal.js/blob/master/scrollReveal.js#L169). This is where ScrollReveal is adding the reset transition styles:

Example Excerpt:
```js
else if ( !visible && elem.config.reset ){
  elem.domEl.setAttribute( 'style',
      elem.styles.inline
    + elem.styles.initial
    + elem.styles.reset // this is the line you don't want
  );
}
```

If I understand the effect you’re after correctly, you should be able to just remove that last `elem.styles.reset`, ending up with something like this:

```js
else if ( !visible && elem.config.reset ){
  elem.domEl.setAttribute( 'style',
      elem.styles.inline
    + elem.styles.initial
  );
}
```
Now remember, this means elements *will not* animate when they leave the viewport… so you may see them disappear abruptly before they’re fully out of view. Presumably, for the effect to work well, you will probably want `vFactor: 0` set in the configuration.

Example:
```js
window.sr = new scrollReveal({ reset: true, vFactor: 0 });
```

Let me know how it works out.

**Comment by jlmakes** [comment]
Hey @JanSchmidhofer 

I think I misunderstood your question at first. ScrollReveal has no notion of scrolling up or scrolling down—it mainly just looks for visibility within the viewport. If you want behavior specific to one scroll direction, you would need to edit the source to:

1. Track scroll direction
2. Check scroll direction before applying reset styles

Assuming you are running the latest master (v2.3.2), that might look something like this:

#### Track Scroll Direction

The event handler around [Line 554](https://github.com/jlmakes/scrollReveal.js/blob/master/scrollReveal.js#L554) would be the ideal place to add our scroll direction logic.

```js
_handler = function( e ){

    if ( !self.blocked ){

      self.blocked  = true;
      self.scrolled = self.scrollY();

      _requestAnimFrame(function(){
        self.animate();
      });
    }
  }
```

All we need to do is compare the new scroll position with the `self.scrolled` property containing the previous position—which might look something like…

```js
_handler = function( e ){

    if ( !self.blocked ){

      // let’s grab the new current position
      var newScroll = self.scrollY();

      // and determine the scroll direction
      self.direction = ( newPos > self.scrolled ) ? "down" : "up";

      self.blocked  = true;
      self.scrolled = newScroll;

      _requestAnimFrame(function(){
        self.animate();
      });
    }
  }
```

#### Check Scroll Direction

Around [Line 169](https://github.com/jlmakes/scrollReveal.js/blob/master/scrollReveal.js#L169). This is where ScrollReveal is adding the reset transition styles:

```js
else if ( !visible && elem.config.reset ){
  elem.domEl.setAttribute( 'style',
      elem.styles.inline
    + elem.styles.initial
    + elem.styles.reset
  );
}
```

You would want to add the check for scroll direction around here, and only apply reset styles when scrolling up. For example:

```js
else if ( !visible && elem.config.reset && self.direction == "up" ){
  elem.domEl.setAttribute( 'style',
      elem.styles.inline
    + elem.styles.initial
    + elem.styles.reset // you may want to try removing this line too
  );
}
```

**Comment by jlmakes** [comment]
**Disclaimer:** I haven’t tested the above, it’s merely an educated suggestion of where to start.

Let me know how it goes.

**Comment by JanSchmidhofer** [comment]
Wow !! Thanks for your support and this solution. 
But if i customize the scrollReveal.js with the code above i get an error - "newPos" is not defined.

**Comment by jlmakes** [comment]
Sorry, that was a typo @JanSchmidhofer. I corrected it, it should be `newScroll`.

**Comment by JanSchmidhofer** [comment]
Ok, now i dont get any errors, but the animation runs on scrolling up and down, nothing changed.
I added a console.log for "self.direction" and i get the output "down" and "up" on scrolling correctly.
I also commented out the "+ elem.styles.reset" but this has no effect. The animation is still running in both directions.

**Comment by jlmakes** [comment]
As I mentioned @JanSchmidhofer, I haven’t tested any of these ideas. I was hoping this would be enough for you to run with it. After all, I don’t know what idea you have in mind.

The last thing I’ll suggest is adding the direction check to [Line 134](https://github.com/jlmakes/scrollReveal.js/blob/master/scrollReveal.js#L134)

```js
// from...
if ( visible ){

// to
if ( visible && self.direction == "down" ){
```

Hope that gets you closer!

**Comment by supadupafly** [comment]
Hi !

I tried too this option (reset only when scroll down).

I replaced the code. That's work good when I scroll down but when I scroll up my elements disapears.

I used data-sr="enter right and move 85px, over 2s reset" on my elements.

**Comment by jlmakes** [comment]
@supadupafly honestly, I didn’t really test any of this… I just tried to get @JanSchmidhofer started. The idea was to only apply reset styles when scrolling up, but it sounds like it needs more work.

If you don’t mind putting together a JS Bin, I don‘t mind spending a little time to help get it working.
