### ISSUE TITLE
Scroll Reveal wait for previous reveal to finish

### ISSUE THREAD

**Issue by hendhyhutomo** [jlmakes/scrollreveal.js#180]
Is there a way to do this automatically without stating the wait? 
I want to create a more cinematic feel to my project.

**Comment by hendhyhutomo** [comment]
The problem about using wait is that it is not rensponsive. I wouldnt know which elements actually needs the wait and which element dont. Maybe adding an animation queue would solve this

**Comment by jlmakes** [comment]
There is nothing baked into ScrollReveal that allows you to easily create animation sequences. Can you be more specific about what you're trying to do? I may be able to offer some guidance on a one-off customization.

**Comment by hendhyhutomo** [comment]
I am trying to create a sequential reveal. So The element reveal by itself one by one when it is in viewport. This works fine if i set a custom wait time for each elemt and set the delay to onload. however for when i scroll down, the element triggred by the scroll are revealed out of the sequence. I wonder if you get what i am trying to do here.

**Comment by hendhyhutomo** [comment]
I try to create this codepen
http://codepen.io/anon/pen/MaQRNm

as you can see when i scroll down, the element that is revealed triggered by the scroll is activated even before the previous elements has finished loading.

I am trying to achieve an sequential animation in a way that the element will wait for the loaded animation to finish even if it is triggered by scroll. 

I set the delay to onload because if i put it as once or always, the element on that is triggered by the scroll will have a long delay before it is being revealed.

**Comment by jlmakes** [comment]
@hendhyhutomo I understand.

In ScrollReveal 3, I think something like this could be possible with callbacks that call `sr.reveal()` on the next element... but I’m suspicious it would be a little messy if you have a lot of elements.

Check out this [demo](http://jsbin.com/gafosufuza/edit?html,css,js,output)

**Comment by evgenyshev** [comment]
Sppasibo for a demo, a very useful feature. How to use this feature different effects? I've tried to add as parameters to the "window.sr = new scrollReveal ({reset: true});", but nothing happened.

**Comment by evgenyshev** [comment]
Maybe I did not put it quite right. How to reduce delay between display of the blocks? :)

**Comment by hendhyhutomo** [comment]
Thank you for the quick respond! @jlmakes

**Comment by jlmakes** [comment]
Related #187

**Comment by Metis77** [comment]
Is there any documentation or a working example?

**Comment by jlmakes** [comment]
@Metis77 There is a link to a working demo above.

**Comment by jlmakes** [comment]
### New In ScrollReveal v3.1
You can now pass a sequence interval (in milliseconds) to the `reveal()` method, making sequenced animations a breeze.
```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```
![sequencer](https://cloud.githubusercontent.com/assets/2044842/13556788/a7dda6c6-e3e2-11e5-93fa-d6a227cbb5dc.gif)

It was a beast to implement, but thanks for the request @hendhyhutomo @Metis77 :bow:

**Comment by hendhyhutomo** [comment]
nice! thanks!!
