### ISSUE TITLE
Problem with FitText.js

### ISSUE THREAD

**Issue by nikmauro** [jlmakes/scrollReveal.js#181]
hello i have problem with FitText.js library, when enable the scrollReveal.js the fittext resize stop working.
Any tip about this?

**Comment by jlmakes** [comment]
I’m not sure @nikmauro, I took a quick look at the `jquery.fitText.js` source, and it's surprisingly small. I’m not sure where the conflict would be. If you put together a [JS Bin](http://jsbin.com) with both ScrollReveal and FitText, I don't mind taking a look.

**Comment by nikmauro** [comment]
@jlmakes  take a look http://jsbin.com/qafacesoni/edit?html,console,output   when disable the data-sr the fittext working, try to resize the output window

**Comment by jlmakes** [comment]
Okay so, sounds like the `resize` event seems to be related to the problem, *but*...

I updated [JS Bin](http://jsbin.com/ticeminegi/edit?html,output) to use ScrollReveal 3 release candidate and it seems to have fixed the problem.

**Comment by nikmauro** [comment]
@jlmakes  take a look in this [JS bin](http://jsbin.com/guhopu/edit?html,output)  scroll down for this problem, if the the content overflow the problem still exist.

**Comment by jlmakes** [comment]
@nikmauro You're right, this is odd.

**Comment by jlmakes** [comment]
Hey @nikmauro!

I really don’t understand where the conflict comes from (the FitText source is crazy simple), but by changing the source order it seems to fix the problem. Check out this [JS Bin](http://jsbin.com/mojokedati/edit?html,output)

**Comment by nikmauro** [comment]
thanks @jlmakes  here the answer from fittext support https://github.com/davatron5000/FitText.js/issues/144
