### ISSUE TITLE
Viewport-Height makes every element visible from beginning?

### ISSUE THREAD

**Issue by davidrot** [jlmakes/scrollReveal.js#182]
Hi,

I'm having some problem. I tried to understand it but not sure why...

The animate function sets all the elements to visible = true, because the isElemInViewport delivers wrong informations.

![auswahl_002](https://cloud.githubusercontent.com/assets/5358167/10918405/c4ca6e1a-8265-11e5-9ed3-b144c8781fa2.png)

I dont have any config in constructor

**Comment by jlmakes** [comment]
Can you confirm what version of ScrollReveal you're using, and the browser?

I recommend checking out [Nordisk's response to issue 111](https://github.com/jlmakes/scrollReveal.js/issues/111#issuecomment-71376102) — here's a relevant excerpt:

>If you have only intrinsic heights on your html/body and no height set AND have set `viewport: window.document.documentElement` [which is the default], the result of  ```sr.getViewportH()``` is *not* the viewport height but the intrinsic height of the ```html``` element...
>
>To get this solved use
>```
html, body {
   height: 100%;
}
```

Let me know if this helps!

**Comment by davidrot** [comment]
I'm using the latest version of scrollReveal and chrome on Linux.
Am 03.11.2015 21:17 schrieb "Julian Lloyd" <notifications@github.com>:

**Comment by jlmakes** [comment]
@davidrot And did you try the suggested fix? The problem described seems very similar.

**Comment by davidrot** [comment]
@jlmakes Yes i tried it right now! Your suggestion solved the problem! Thank you for your fast help! :)

**Comment by jlmakes** [comment]
Glad it worked out @davidrot, I’m thinking I need to revisit this anyway… at the very least include this in the Wiki Tips section, or perhaps look into refactoring the source. :bow:

**Comment by challahan** [comment]
Yes please add this to the instructions or Wiki - I spent a couple of hours of frustration trying to get this to work until I discovered this post!

**Comment by jlmakes** [comment]
@challahan Any chance you could upload a [JSbin](http://jsbin.com) demonstrating the problem? I’m trying to recreate the problem, and I’m not having any luck.

Also, what version of ScrollReveal are you using?
