### ISSUE TITLE
Horizontal viewport detection

### ISSUE THREAD

**Issue by radubalta** [jlmakes/scrollreveal.js#184]
I had to use this cool library in a slider but the viewport detection was not fired. So i personally implemented detection for horizontal viewport.

**Comment by jlmakes** [comment]
I’d be interested to take a look at your changes. Are you willing to share them?

**Comment by radubalta** [comment]
Yea man, sorry for the delay. I have added: 

getViewportW: function(){

      var client = self.config.viewport['clientWidth'];
      var inner  = window['innerWidth'];

      if ( self.config.viewport === window.document.documentElement ){
        return ( client < inner ) ? inner : client;
      }

      return client;
    }


and changed isElemInViewport: function( elem ) with; 

function confirmBounds(){

        var top        = elTop + elHeight * vFactor;
        var bottom     = elBottom - elHeight * vFactor;
        var left       = elLeft + elWidth * vFactor;
        var right      = elRight - elWidth * vFactor;
        var viewBottom = self.scrolled + self.getViewportH();
        var viewTop    = self.scrolled;
        var viewRight  = 0;
        var viewLeft   = self.getViewportW();

        var result = ( top < viewBottom ) && ( bottom > viewTop ) && (right > viewRight ) && ( left < viewLeft );

        return result;
      }

**Comment by jlmakes** [comment]
Cool stuff @radubalta!

I’m just wrapping up the `3.0` documentation, and then I’ll look at adding this into the next release. :beers:

**Comment by jlmakes** [comment]
This came up again, so bumping up the priority.

**Comment by radubalta** [comment]
Nice :D

**Comment by jlmakes** [comment]
![horizontal-scroll](https://cloud.githubusercontent.com/assets/2044842/11521407/bcce8594-98a3-11e5-83a1-911dfb982f47.gif)
