### ISSUE TITLE
Additional support for opacity

### ISSUE THREAD

**Issue by nohuex** [jlmakes/scrollReveal.js#185]
Not sure whether this is already achievable, but it would be great if the fading in effect would take into account an element set opacity.

For example, an element in my page is set to appear at opacity: 0.6 in the CSS. Can the Reveal transition start at 0 and stop at 0.6? It seems it goes all the way to 1, then quickly drops to 0.6.

Thank you for such a great plugin.

**Comment by jlmakes** [comment]
Interesting!

It’s already possible to change the configuration (including target opacity) for specific elements, but it sounds like you want ScrollReveal to detect the computed opacity automatically.

I think by default, that’s a pretty cool idea! I’ll play around with `window.getComputedStyle( el )` and see about adding this to ScrollReveal. Thanks @nohuex!

:bow:

**Comment by jlmakes** [comment]
Baked this into 3.0, and I’m also looking into doing the same for rotate and scale transforms.

re: [Get Value of CSS Rotation through JavaScript](https://css-tricks.com/get-value-of-css-rotation-through-javascript/)

Thanks again @nohuex!

**Comment by nohuex** [comment]
No, thank you!
