### ISSUE TITLE
vFactor and collapsed items

### ISSUE THREAD

**Issue by nohuex** [jlmakes/scrollReveal.js#186]
There seems to be an issue with detecting items and trigger animations in the following scenario:

- A div containing menu <li> items is set to visibility hidden
- Menu items are set to be revealed in a sequence (with increased delay on each item, and vFactor set to 0)
- A button toggles this menu open, to revel the menu items in sequence

The desired effect was for the animation sequence to begin as soon as the menu dig expands, but instead the menu <li> items remain hidden until a tiny amount of scroll is triggered manually.

Is there a way to detect and animate them without scrolling?

Thank you!

**Comment by jlmakes** [comment]
Are you using ScrollReveal `2.3.2` or `3.0-RC`?

First though is to try calling `sr.init()` after the menu animation completes.

**Comment by nohuex** [comment]
sr.init() does the trick, at least initially. All I have to figure out is how to reset it whilst collapsed, so each time you expand the menu, the menu items enter in a sequence.

I'm using 2.3.2. I'll look into the new version asap :)

**Comment by jlmakes** [comment]
Assuming `v2.3.2.`

Using `init()` will scan the DOM and initialize animations. If you want to reset ScrollReveal, you could try nuking the element store:

*Example (v2.3.2):*
```js
sr.elems = {};
sr.init();
```

If you wanted to do the same with `v3.0-RC` it would be:

*Example (v3.x):*
```js
sr.store.elements = {};
sr.init();
```

:bow:

**Comment by nohuex** [comment]
Ok will give it a go. Thank you again :)
