### ISSUE TITLE
Sequenced Animations

### ISSUE THREAD

**Issue by bdthemes** [jlmakes/scrollreveal.js#187]
Hello, I think it's a good idea if you add function for children item animation automatically. is it possible to add the this features in future? here an example script:

http://zavoloklom.github.io/material-design-hierarchical-display/

**Comment by jlmakes** [comment]
What you’re asking for seems less about animating children automatically, but rather, creating animation sequences on an element set. This has come up before (see #180 for a manual solution) and is something I have been considering for a while.

**Comment by jlmakes** [comment]
### New In ScrollReveal v3.1
You can now pass a sequence interval (in milliseconds) to the `reveal()` method, making sequenced animations a breeze.
```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```
![sequencer](https://cloud.githubusercontent.com/assets/2044842/13556788/a7dda6c6-e3e2-11e5-93fa-d6a227cbb5dc.gif)

It was a beast to implement, but thanks for the request @bdthemes :bow:

**Comment by bdthemes** [comment]
Many many thanks @jlmakes :)
