### ISSUE TITLE
Not working with semantic-ui?

### ISSUE THREAD

**Issue by Maxhodges** [jlmakes/scrollReveal.js#188]
I tried everything I could think of, but can't get it to work in semantic-ui. Anyone have similar problems and any workarounds?

Do I need jquery? If so, what version? I'm using:
```html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
```

You can see my project source here:
https://github.com/white-rabbit-japan/wreHomePage/tree/feature/scrollReveal

Cheers! :beers:

**Comment by Maxhodges** [comment]
do I need jquery? what version?

**Comment by Maxhodges** [comment]
sharing repo here
https://github.com/white-rabbit-japan/wreHomePage/tree/feature/scrollReveal

**Comment by jlmakes** [comment]
ScrollReveal does not require jQuery.

Are there any errors in the console? If you check the `sr` object in the console, is it defined and does it contain an `elems` object?

**Comment by Maxhodges** [comment]
Hi @jlmakes  thanks for the reply. I can sr in console and see that it was uninitialized.  I ran init() and that fixes it. I thought it was suppose to self-initialize. Maybe mentioning that we need to run init() in the docs would spare others a great deal of time. 

![image](https://cloud.githubusercontent.com/assets/957271/11322034/a618f23e-911a-11e5-8113-b9aa82b90bee.png)


Cheers!

**Comment by Maxhodges** [comment]
except for my init() problem, scrollReveal is fantastic. Thanks so much for taking the time to share it!

**Comment by jlmakes** [comment]
>I thought it was suppose to self-initialize. Maybe mentioning that we need to run init() in the docs would spare others a great deal of time.

You’re right, and previous versions _did_ automatically initialize on instantiation.

The main reason is that with the new JavaScript API in 3.0, it’s necessary to separate the instantiation and initialization—simple example:
```js
// instantiate
window.sr = new scrollReveal();

// use JS API to configure reveals
sr.reveal( '.myClassSelector', "enter top after 1s" );

// initialize
sr.init();
```

I’m working on updating the docs for 3.0 right now! :bow:

**Comment by Maxhodges** [comment]
here's what I made with it
https://www.whiterabbitexpress.com/

Thanks for scrollReveal!

**Comment by jlmakes** [comment]
@Maxhodges Awesome, it’s my pleasure.
