### ISSUE TITLE
v3 ScrollReveal function name bug?

### ISSUE THREAD

**Issue by pauliwago** [jlmakes/scrollReveal.js#191]
In V2, you have your main ScrollReveal function camel-cased (scrollReveal) while in V3, you changed it so it's now ScrollReveal.  This breaks the call to the function when going from v2 to v3 because Javascript is case sensitive. 

Also in your ScrollReveal 3 PR documentation (https://github.com/jlmakes/scrollReveal.js/pull/168), you left the call to the function camel-cased so it won't work.

```js
window.sr = 
  new scrollReveal( defaults 
    .reveal( '.foo', myReveal )
    .reveal( '.bar', 'vFactor 0.2 and enter left' )
    .init();
```

**Comment by jlmakes** [comment]
Thanks for trying 3.0 @pauliwago 

>"This breaks the call to the function when going from v2 to v3 because Javascript is case sensitive."

You are correct. **ScrollReveal 3 is going to be a massive (and breaking) upgrade**. The issue raised in #176 has prompted the change you’re talking about, and I’ve updated the PR documentation sample code.

Sorry for the confusion, you’ve caught things mid-transition as I plan to launch very soon. If you’ll look, you’ll see even the [demo site](http://scrollrevealjs.org) is down. Only a few more days before I tie the loose ends.
