### ISSUE TITLE
ScrollReveal thinks element is visible even when it is not on page load

### ISSUE THREAD

**Issue by pauliwago** [jlmakes/scrollReveal.js#192]
Hello,
I'm having a strange issue where ScrollReveal thinks elements are visible when it's actually not (and therefore, reveals the animation prematurely).  This happens only on page load and only when the element is below the loaded viewport but not too far below it (if the element is very far down from the viewport or above it, the animations show at the correct time).

So say I have 4 elements:
- Element A: Located halfway above the current viewport such that the bottom half of the element is visible without scrolling
- Element B: Located smack in the middle of the viewport
- Element C: Located halfway below the current viewport such that the top half of the element is visible without scrolling
- Element D: Located much further down the page such that a good amount of scrolling is required to see it

I set the above elements with a really high vFactor (~0.9).  When I refresh the page, this is what happens:
1.) Element B does its animation as expected on page load
2.) Scrolling up, A does its animation as soon as I reach the 0.9 threshold, which is as expected.
3.) However, scrolling down, C does not animate because it already did on page load along with Element B.  The expected behavior should be the image should animate only when I scroll past the 0.9 threshold.  Instead, it animated on page load even though only ~0.5 threshold was reached.
4.) If I scroll further down, D animates only when I reach the 0.9 threshold as expected.  In other words, it does not animate at the ~0.5 threshold that triggered Element C during page load.

What's interesting is even when Element C is located even further down the viewport such that the element is completely below the viewport and not visible at all, it STILL thinks some threshold was crossed because when I scroll down, the element is already there with no reveal animation.  However, as mentioned above, when the element is located very far below the viewport like with Element D, it works as expected.

So I guess somehow when ScrollReveal runs init() initially on page load, it's overestimating the visibility of elements below the current viewport.  I'm not sure what could be the cause....any ideas?  I set my html, body height to 100% and it looks like clientHeight, offset are accurate.

Thanks!

**Comment by jlmakes** [comment]
Hey @pauliwago,

I assume you’re using 3.0, and I’m pushing fixes/updates to the 3.0.0-RC branch multiple times a day as things move closer and closer to launch. My last commit was actually a fix to `getViewportSize`, where I had used `clientWidth` twice.

This might cause odd behavior where ScrollReveal thinks the viewport is as tall as it is wide. Please pull the latest, and see if you still have this problem.

**Comment by pauliwago** [comment]
Hi @jlmakes 

Thanks for getting back to me so quickly.  I just tried it with the latest RC from the branch and it still exhibits the same behavior (I think the version I tried it on earlier was the same one since I was doing this late last night).  Actually this behavior is exhibited on the latest v2 release in the master branch as well...which is why I tried using 3.0 thinking maybe the bug was fixed.  Do you have any top of mind recommendations to debug?  I'm using Bootstrap.  Otherwise, I will continue to debug and keep you updated with what I find.

Thanks!

**Comment by jlmakes** [comment]
Do you think it’s possible to put together a simple online demo of the bug?

In my local tests, vFactor and element visibility work as intended. I’m curious if this is a 3rd party conflict, or if I’m missing something.

**Comment by pauliwago** [comment]
Sure thing!  I will put something together when I get home from work
tonight.  It could very well be a 3rd party conflict...


Paul

**Comment by pauliwago** [comment]
Hi @jlmakes 
Just wanted to give you an update: I ended up trying it at home again and turns out it was a 3rd party conflict.  I put the scrollReveal function before another function that changes the height of an element.  I'm guessing what happened was that scrollReveal calculates the height initially and the 3rd party function caused the position of elements under it to change but scrollReveal didn't recalculate.  I just moved the scrollReveal function to the bottom and all is good now :)

Thanks for your help!

**Comment by jlmakes** [comment]
Awesome! Glad it worked out @pauliwago :beers:

**Comment by ismaelyws** [comment]
@jlmakes I think I have an issue similar to this but I cannot figure out what is causing it.

Images load once the page is loaded, and then the scroll reveal effect kicks in.

So it looks like the images "flash" or load twice.

You can see here http://dev.ivgserver.com/verb-pro/

BTW, I love the plugin and I would like to donate. I hate asking for support for a free item.

**Comment by jlmakes** [comment]
I appreciate the thought @ismaelyws! I'm working on some improvements for early 2017, and there'll be ways to some new ways to support ScrollReveal :)

In regards to your question, it sounds like your scripts are at the bottom of your page (as is recommended practice)... but that means your page loads a bunch of content before your JavaScript runs, and in this instance, before ScrollReveal can hide your elements.

If this is indeed what the problem is, you'll want to apply `visibility: hidden` to all elements you're revealing... so that they load hidden. ScrollReveal will add `visibility: visible` as it reveals your elements, so you won't get that "flash" on page load.

You don't want to add `visibility: hidden` if ScrollReveal isn't supported though, but there's a way to handle this. **You can read a little more about that here: [Docs 4.2. Improve User Experience](https://github.com/jlmakes/scrollreveal#42-improve-user-experience)**

Please keep in mind, there may be some changes to this strategy in the upcoming version of ScrollReveal... for example, the unreleased development version will automatically add `.sr` to `<html>` if a supported browser is detected.

If that doesn't solve your issue, feel free to open a new issue.

**Comment by ismaelyws** [comment]
That makes sense. I'll give it a shot.

And yes, I'll definitely donate when you have options available in 2017.

**Comment by ismaelyws** [comment]
Just tried what you recommended and it worked perfectly.

Now I should tweak the image sizes a little.

**Comment by Generic-methodelastic** [comment]
I met the same problem and created a strategy to resolve it https://stylesheets.space/questions/tips-on-creating-animations-for-elements-that-are-triggered-when-scrolling-and-become-visible
