### ISSUE TITLE
Can't access scrollreveal on NPM

### ISSUE THREAD

**Issue by clayne11** [jlmakes/scrollreveal.js#195]
I cannot access scrollreveal on NPM.

<img width="1277" alt="screen shot 2015-12-18 at 12 30 50 am" src="https://cloud.githubusercontent.com/assets/2831444/11890088/a28ce086-a51e-11e5-89a6-9899832f2bb8.png">

Is says there are no versions and no README

**Comment by jlmakes** [comment]
you're right @clayne11, I’ve been working with NPM support since yesterday on this.

**Comment by jlmakes** [comment]
I had some issues with `v3.0.0` and due to security reasons, NPM won't let me re-submit that version of the library.

However, @clayne11 I’m working on #193 and #196 right now, at which point I will release `v3.0.1` (likely on Monday) and ScrollReveal will be back on NPM.

**Comment by jlmakes** [comment]
<img width="1713" alt="screen shot 2015-12-21 at 8 54 39 pm" src="https://cloud.githubusercontent.com/assets/2044842/11939840/1b58a7b2-a825-11e5-9246-7892d5efa034.png">

**Comment by jlmakes** [comment]
The latest version `2.3.3` and `3.0.3` are available on NPM, and the hiccups are behind us. My apologies, I had to learn the hard way how strict NPM is with package version history.

It’s your prerogative, but if you don't mind, please un-publish your [forked package](https://www.npmjs.com/package/scrollreveal-fork). I have a number of updates planned, and I feel it will only serve as a confusion.

Thanks for your help @clayne11! :bow:

**Comment by clayne11** [comment]
Done.
