### ISSUE TITLE
Not working when element already has transition

### ISSUE THREAD

**Issue by JuhG** [jlmakes/scrollreveal.js#197]
If the element already has a transition attribute via CSS, it won't be animated on load. This only happens if the element is visible on load, otherwise it works on scroll. But to keep the look of the website consistent I had to remove the already existing transitions.

**Comment by jlmakes** [comment]
You know what @JuhG, there’s no good reason I hadn't already stored the computed transition styles. Thanks for your feedback!

I added this and bumped to `v3.0.2` :bow:
