### ISSUE TITLE
AJAX not working when initial list is empty

### ISSUE THREAD

**Issue by noclat** [jlmakes/scrollreveal.js#198]
I am using **Vue.js** and items get loaded only after my AJAX call. So the list starts empty, like this:

```html
<div id='container'>
<div class='tile' v-for='item in items'><!-- … --></div>
</div>
```

```js
window.sr = ScrollReveal().reveal( '.tile', { container: document.getElementById('container') } );
```

and I get the following warning:

```
reveal(".tile"") returned 0 elements.
```

and then, when I try `sr.sync()`:

```
Uncaught TypeError: Cannot read property 'sync' of undefined
```

**Comment by jlmakes** [comment]
ScrollReveal returns a warning if no elements are found, and since you are chaining the method… `window.sr` does not get assigned correctly.

What I would suggest is doing a simple conditional _inside_ your AJAX callback—something like:
```js
if ( !sr ) {
  var container = document.getElementById('container');
  window.sr = ScrollReveal().reveal( '.tile', { container: container } );
} else {
  sr.sync();
}
```
This way, you instantiate and chain to a reveal _after_ the first batch of elements has loaded, but the second batch will only `sync()`.

What do you think?

**Comment by jlmakes** [comment]
I’ll also mention that, you may want to use ScrollReveal in other places… not just for `.tiles` in `item in items`. In that case, I would instantiate ScrollReveal separately, somewhere earlier in your code.

Here I will use a a flag to track our first AJAX call.

_Example:_
```js
// index.js
window.sr = ScrollReveal();
var flag  = true;
```
```js
if ( sr && flag ) {
  var container = document.getElementById('container');
 sr.reveal( '.tile', { container: container } );
} else {
  sr.sync();
}
```
This is essentially the same solution, but allows you to use ScrollReveal throughout your project without relying on the first AJAX call to instantiate it.

:beers:

**Comment by noclat** [comment]
I understand that I need to instantiate first, thanks for your time!

**Comment by jlmakes** [comment]
@noclat there's nothing wrong with chaining, but if you chain to an empty reveal… the returned value will be a warning, not the ScrollReveal instance. :bow:

Happy holidays!
