### ISSUE TITLE
Can't install with Codekit, not finding on Bower

### ISSUE THREAD

**Issue by dlewand691** [jlmakes/scrollreveal.js#200]
Trying to install thru Codekit but failing with this error: 

> Bower failed to install 'scrollReveal.js'. It returned this error information:

> Code & Message: ENOTFOUND, **Package scrollReveal.js not found**

> Try these steps to fix general errors:

>1. Be sure you're connected to the Internet.
2. If you are running any blocking/security apps like Little Snitch or Antivirus software, disable those.
3. If you have installed Apple's Developer Tools, launch Xcode, accept the license terms and let the installation routine finish.
4. Make sure your network or firewall is not blocking the default port for git:// URLs, which is 9418. (Corporate networks do this frequently.) Use the "Tasks" menu to switch Git to use https:// URLs instead.
5.Delete the hidden ".cache" directory in your home folder.

**Comment by jlmakes** [comment]
The bower package name looks incorrect, it should read `scrollreveal`
