### ISSUE TITLE
Cannot install old versions via npm

### ISSUE THREAD

**Issue by rawcreative** [jlmakes/scrollreveal.js#201]
It appears that all older versions of scrollreveal have been removed from the npm registry. The only version available to install is 3.0. Trying to run npm install on an existing project that uses version 2.x fails.

**Comment by isaacs** [comment]
Should be fixed now.

This is an important lesson about the hazards of `unpublish -f`, but also, the valuable safety net of using `npm version` instead of manually editing package.json, so that there's a history of git tags to fall back on :)

**Comment by jlmakes** [comment]
@rawcreative it looks like you can now use `2.3.3` on npm, which is a patched version of `2.3.2`.
