### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by cornerolive** [jlmakes/scrollreveal.js#202]
Hi,

The code:

    https://cdn.jsdelivr.net/scrollreveal.js/3.0.2/scrollreveal.min.js

Does not work. 

Thank you

**Comment by jimaek** [comment]
3.0.3 was uploaded correctly but there was a deployment delay with 3.0.2 unfortunately. Its fixed now, sorry about that,

**Comment by jlmakes** [comment]
Thanks @jimaek!
