### ISSUE TITLE
Best use practice with WordPress?

### ISSUE THREAD

**Issue by paaljoachim** [jlmakes/scrollreveal.js#203]
Hey

I am just wondering about best use tips with using it in WordPress.

Thanks.

**Comment by jlmakes** [comment]
Hi @paaljoachim,

I recommend WordPress’ guide to [Using JavaScript](https://codex.wordpress.org/Using_Javascript), and the [ScrollReveal Tips](https://github.com/jlmakes/scrollreveal.js#4-tips) in the documentation. 

Remember, if everything reveals, it cheapens the effect. It’s best to reveal key elements that you want extra attention drawn to, or supporting elements that don't need to be seen right away. In other words, salt wisely, you can always add more—but add too much, and you ruin the meal.

:beers:

**Comment by paaljoachim** [comment]
Thanks!
