### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by francisco33** [jlmakes/scrollreveal.js#204]
In IE9 I cannot see the items, I think that's opacity: 0;
How can I solve that?

Thanks

**Comment by jlmakes** [comment]
@francisco33 [IE9 does not support CSS transitions](http://caniuse.com/#search=transitions).

There is not much that can be done here, as ScrollReveal does not fallback to JavaScript animation.

**Comment by jlmakes** [comment]
@francisco33 can you check [the demo](https://scrollrevealjs.org) again to confirm that the blocks are at least visible?
