### ISSUE TITLE
I can't seem to install from bower

### ISSUE THREAD

**Issue by bmcorser** [jlmakes/scrollreveal.js#206]
With bower 1.5.2 when I run `bower install scrollreveal` I just get:

```
bower ENOTFOUND     Package scrollReveal.js not found
```

**Comment by bmcorser** [comment]
#200 seems relevant, but was closed recently?

**Comment by bmcorser** [comment]
http://bower.io/search/?q=scrollreveal is empty

**Comment by bmcorser** [comment]
`bower install scrollreveal\#2.1.0` lets me install

**Comment by jlmakes** [comment]
I’ve had such a nightmare with `npm` and `bower` with the release of `3.0.0`

The previous issue was closed since the name was presumed incorrect, but if the package itself (with the correct name) is failing, it may indeed be a different issue. @bmcorser

**Comment by jlmakes** [comment]
@bmcorser http://bower.io/search/?q=scrollreveal is indeed empty but if you type `bower info scrollreveal` all the packages are shown.

Also, I’ve tested a few installs… and everything appears to be working correctly.
```console
bower install scrollreveal
bower install scrollreveal#2.3.2
bower install scrollreveal#2.1.0
etc...
```

I did change the package name from `scrollReveal.js` to `scrollreveal` but everything should work with the new package name. Can you please confirm?

**Comment by bmcorser** [comment]
I feel like I'm missing something. Do I need to blow away a cache somewhere?

**Comment by jlmakes** [comment]
@bmcorser you could try…
```console
➜ bower cache clean
➜ bower cache clean <name> [<name> ...]
➜ bower cache clean <name>#<version> [<name>#<version> ..]
```

**Comment by bmcorser** [comment]
Thanks for all the feedback, our build process seems to be back online. The front end team will be happy (when they come back to work!)

:stars:

**Comment by jlmakes** [comment]
Awesome! :bow:
