### ISSUE TITLE
ScrollReveal is not defined with webpack

### ISSUE THREAD

**Issue by marciomunhoz** [jlmakes/scrollreveal.js#209]
When using ScrollReveal with webpack, the object ScrollReveal is not defined.
Have someone experienced the same issue?

Thanks!

**Comment by volnei** [comment]
+1 with last version

**Comment by tamamadesu** [comment]
same question!

**Comment by tforssander** [comment]
I noticed a similar error when updating to the 3.0.3 release and noticed that I needed to change from `window.sr = new scrollReveal(config);` to `window.sr = ScrollReveal(config);` (notice the uppercased S).

**Comment by volnei** [comment]
I have tried with all possible cases with no success. The error appears when lib is loaded.

**Comment by jlmakes** [comment]
@volnei @marciomunhoz @tamamadesu I’m not that familiar with Webpack yet, but my initial suspicion would be calling without the `new` keyword expects `window == this`
```js
function ScrollReveal( config ) {
  if ( window == this ) {
    return new ScrollReveal( config );
  }
  // etc...
```
Maybe try using `new ScrollReveal()` (with the `new` keyword) inside Webpack? Just swinging in the dark here…

**Comment by volnei** [comment]
The error occurs on return ScrollReveal; at line 473 of file https://github.com/jlmakes/scrollreveal.js/blob/master/dist/scrollreveal.js

I think is caused by a package tooling used to build the dist. Maybe this is incompatible with webpack?

**Comment by volnei** [comment]
I think this is generated by gulp on config umd({ namespace: 'ScrollReveal', exports: 'ScrollReveal' }), but i'm not familiar with gulp... =/

**Comment by jlmakes** [comment]
@volnei That was my other suspicion… the module wrapper. Is it possible to test to clone the repo and test the source `scrollreveal.js` in the root, instead of the dist files?

**Comment by volnei** [comment]
@jlmakes it works by using the scrollreveal.js (before wrap) but need a change in the code at line 456

from 

´´´
  var _requestAnimationFrame = this.requestAnimationFrame       ||
                               this.webkitRequestAnimationFrame ||
                               this.mozRequestAnimationFrame;
´´´

to 

´´´
  var _requestAnimationFrame = window.requestAnimationFrame       ||
                               window.webkitRequestAnimationFrame ||
                               window.mozRequestAnimationFrame;

´´´

Hope this helps

**Comment by volnei** [comment]
If you are interested to investigate, I just create a repo with an example app to simulate the problem.

https://github.com/volnei/webpack-scrollreveal

Clone the repo
npm install
npn run build

And open the index.html file.
Ps. You need to follow this steps https://github.com/jlmakes/scrollreveal.js/issues/209#issuecomment-167904016

**Comment by jlmakes** [comment]
Thanks @volnei I will explicitly reference `window` in the next release. :bow: 

I can only assume there are plenty of packages using a wrapper for module loading, I wonder what others are doing for Webpack compatibility.

**Comment by volnei** [comment]
For reference...  https://github.com/nnnick/Chart.js it working :smile:

**Comment by jlmakes** [comment]
@volnei Interestingly enough, [this issue](https://github.com/jquery/globalize/issues/441) talks about something very similar. It seems the AMD definition is failing for some reason, and the author achieved success merely by reversing the conditional to test for CommonJS first.

I tried doing this and received a different error from Webpack:
```console
WARNING in ./~/scrollreveal/dist/scrollreveal.js
Critical dependencies:
4:29-36 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/scrollreveal/dist/scrollreveal.js 4:29-36
```

**Comment by jlmakes** [comment]
@volnei First, I believe I’ve confirmed this part of your `index.js` needs to be changed:
```diff
- import {ScrollReveal, Tools} from 'scrollreveal'
+ import ScrollReveal from 'scrollreveal'

window.sr = ScrollReveal()
window.sr.reveal('.box')
```
Secondly, it seems that my new IIFE structure needs to have its UMD wrapper exports updated:
```diff
gulp.task( 'dist', function() {
  gulp.src('scrollreveal.js')
-    .pipe( umd({ namespace: 'ScrollReveal', exports: 'ScrollReveal' }) )
+    .pipe( umd({ namespace: 'ScrollReveal', exports: 'this.ScrollReveal' }) )
    .pipe( gulp.dest('dist') )
});
gulp.task( 'dist:minify', function() {
  gulp.src('scrollreveal.js')
-    .pipe( umd({ namespace: 'ScrollReveal', exports: 'ScrollReveal' }) )
+    .pipe( umd({ namespace: 'ScrollReveal', exports: 'this.ScrollReveal' }) )
    .pipe( uglify() )
    .pipe( rename('scrollreveal.min.js') )
    .pipe( gulp.dest('dist') )
})
```
After making these changes…
![webpack-sample](https://cloud.githubusercontent.com/assets/2044842/12054530/9ac820a8-af24-11e5-8d71-155e02ade3a2.gif)

I published v3.0.5 with the necessary changes, and have confirmed it is working with Webpack.

**Comment by volnei** [comment]
Thank you a lot @jlmakes. Now it works fine :smile:

**Comment by jlmakes** [comment]
:+1:

It’s my pleasure @volnei. Thanks for helping make ScrollReveal better, I appreciate it.

**Comment by jlmakes** [comment]
Why two thumbs down @katalonne?

**Comment by yarhtut** [comment]
👍 Thanks, @jlmakes

**Comment by birksy89** [comment]
For me the issue was the capitalisation:

This works:
import ScrollReveal from 'scrollreveal'

 window.sr = ScrollReveal();

This didn't:
import 'scrollreveal'

**Comment by lucian95** [comment]
Tried with the latest version (3.3.6) and did not work with webpack, but when I reverted to scrollreveal@3.0.5 it worked just fine.

**Comment by jlmakes** [comment]
Can you do me a favor and test with `scrollreveal@beta` please @lucian95?

**Comment by lucian95** [comment]
Sure thing. It did load from webpack but it only contained an "__esModule" and "default" property. Is that the object you intended to return with "require('scrollreveal')"? Seems off.

![scrollreveal beta](https://user-images.githubusercontent.com/17990875/34910043-64cd5872-f87b-11e7-80af-5294c2941e43.png)

**Comment by jlmakes** [comment]
That looks like the result of a the [Babel ES2015 to Common JS Plugin](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) @lucian95.

I'm not sure, but seems like if you're going to consume the default export of a ES2015 module with Babel v6+, you'd need to do this:

```js
const ScrollReveal = require('scrollreveal').default
```

Also mentioned in the Babel documentation, is a plugin that automatically unboxes the default property value as Node's `module.exports`, called [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports)... which as I understand should allow you to write:

```js
const ScrollReveal = require('scrollreveal')
```

**Comment by lucian95** [comment]
In that case yes, doing "require('scrollreveal').default().reveal(...)" works properly. I tried it again just now.

**Comment by thanhitkeaung09** [comment]
my scrollreveal is not defined in vite , can you guys suggest me what to do .
