### ISSUE TITLE
Elements within viewport not loading until scroll

### ISSUE THREAD

**Issue by MartinDM** [jlmakes/scrollreveal.js#213]
There seem to be a couple of issues raised about this bug but appear without clear resolution.

On first load, until you scroll, the in-view elements don't fade in. May need to resort to faking a nudge to trigger the action..

Is there perhaps a parameter that can be passed to the config object to specify elements which should load right away? Maybe a different way to do this? Will update if I can work around it :)

Thanks. Martin

**Comment by jlmakes** [comment]
Are you using any 3rd party libraries or frameworks? A lot of users that run into visibility issues tend to be using 3rd party code, causing ScrollReveal’s onload logic to access a DOM that's mid-change.

Also, what browser? Can you put together a [jsbin](http://jsbin.com) that shows it?

**Comment by jlmakes** [comment]
@MartinDM Any news?
