### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by mitchellknight** [jlmakes/scrollreveal.js#219]
I can't seem to find documentation on what browsers scrollreveal.js supports. Could we add this to the readme or wiki?

**Comment by jlmakes** [comment]
Good idea @mitchellknight 

The short answer is browsers that support CSS Transform and CSS Transition, which is IE10+ and modern browsers.

**Comment by jlmakes** [comment]
@mitchellknight https://github.com/jlmakes/scrollreveal.js#51-browser-compatibility

I made some improvements to the configuration section while I was at it, the README looks a lot better. Thanks for the suggestion!  :bow:
