### ISSUE TITLE
Scroll animation Firefox browser support?

### ISSUE THREAD

**Issue by ocvninfo** [jlmakes/scrollreveal.js#220]
Scroll animations still work correctly on any browser but. But it doesn't work on Firefox.
I see this notice in console *ScrollReveal is not supported in this browser.*
Hope this will be fixed ASAP!

**Comment by tideg** [comment]
I can confirm this! Seems like in sr-version 3.0.8 Firefox (mine is 43.0.4) is recognized as unsupported.

**Comment by jlmakes** [comment]
@ocvninfo @tideg Thanks for the heads up. I changed how support is detected in 3.0.8, and it should be a 1 liner to fix.

I'll patch this up and put out 3.0.9 in a few hours. :bow:

**Comment by jlmakes** [comment]
Cheers @tideg and @ocvninfo :beers:

**Comment by ocvninfo** [comment]
@jlmakes Good work.
Cheers !!!
