### ISSUE TITLE
data-sr is not working anymore?

### ISSUE THREAD

**Issue by reidark** [jlmakes/scrollreveal.js#224]
Hello.

After your update, the data-sr is not working anymore?

**Comment by jlmakes** [comment]
> #### 5.2. Issues and Reporting Bugs

>_Please search existing issues, before creating a new one_; every issue is labeled and attended carefully. If you open a duplicate issue, it will be closed immediately.

Duplicate of #194 #205 #207

**Comment by jlmakes** [comment]
Hi @reidark,

This has been discussed quite a few times already, but yes version 3 is a breaking release that re-imagines the primary API with a more modern and robust strategy. Please see the other issues (especially #194) if you have more questions.

Thanks @reidark :bow:
