### ISSUE TITLE
希望在easing参数中支持jquery.easing

### ISSUE THREAD

**Issue by houguang** [jlmakes/scrollreveal.js#225]
如何，希望改进此功能

**Comment by jlmakes** [comment]
Unfortunately, I do not speak Chinese. Google has helped me out a little to translate:

>"We hope to improve this functionality"

ScrollReveal uses CSS for animation, not JavaScript. For this reason, all easing is handled through CSS—it’s fundamentally not possible to utilize jQuery easing functions, without re-writing ScrollReveal to animate using JavaScript.

You should however be able to create some more unique easing with [cubic-bezier](http://cubic-bezier.com/#.17,.67,.83,.67), but this is presently the limit of what’s possible.

**Comment by houguang** [comment]
cubic-bezier 不是支持所有缓动效果

**Comment by jlmakes** [comment]
@houguang I know that, but it is all that is supported. It is **not possible** to use jQuery easing functions inside of CSS transitions.

The easing must be in CSS.
