### ISSUE TITLE
data-scrollreveal or data-sr not working

### ISSUE THREAD

**Issue by mohsinali1317** [jlmakes/scrollreveal.js#232]
data-scrollreveal or data-sr not working is not working. I read in the issues that it is not supported anymore. But can you tell me what is the alternative for this 

    data-scrollreveal="enter left after 0.15s over 1s"

in JavaScript?

**Comment by mohsinali1317** [comment]
No I am using the previous version 2.3.2 but the animation doesn't seem to work properly. Here I made a fiddle http://jsfiddle.net/zczc93vr/106/. The idea to reveal from left but it just doesn't work.

**Comment by jlmakes** [comment]
@mohsinali1317 The default animation has a `0px` distance.

In order to see the animation you expect, add a `move` keyword, such as:
```html
<div data-sr="move 50px and enter left over 1s">
    <h1>I enter from the left of the screen</h1>
</div>
```

Demo: http://jsfiddle.net/zczc93vr/114/
