### ISSUE TITLE
Remove console.log from minified distribution

### ISSUE THREAD

**Issue by matt3224** [jlmakes/scrollreveal.js#235]
Title says it all. Thanks!

**Comment by jlmakes** [comment]
@matt I tried to update the `Gulpfile.js` and the contained `gulp-uglify` configuration with `drop_console: true`, but it did not work. Any ideas?

**Comment by matt3224** [comment]
Not sure looks right, I use CodeKit to do all that jazz.

**Comment by jlmakes** [comment]
Finally got this one handled using `gulp-strip-debug` @matt3224 :bow:
