### ISSUE TITLE
not working on horizontal swiper slider

### ISSUE THREAD

**Issue by rlech** [jlmakes/scrollreveal.js#236]
using this with [framework7 swiper slider ](http://idangero.us/swiper/#.Vtc9LsdjoUE) to animate some buttons on the last page but it looks like the "isInViewPort" event is not fired. Its only working on the first page from my slider

**Comment by jlmakes** [comment]
It’s hard to know where to start, combining two libraries that use position and visibility. I’m not familiar with Swiper, but it seems to use side by side tiles...

![swiper](https://cloud.githubusercontent.com/assets/2044842/13517216/a6e95bca-e1c1-11e5-8063-a368d9aed5de.gif)

ScrollReveal considers anything in the configured viewport as _visible_ based on it's position. Opacity and CSS transforms will not impact the truthy visibility of elements. I’m not 100% clear on the problem you’re having, but I can already see a conflict attempting to combine these two libraries.

The first idea that comes to mind involves forking ScrollReveal to make the `_isElemVisible(elem)` method public (ie. `ScrollReveal.prototype.isElemVisible(elem)`), and using the Swiper API callbacks `onSlideChangeStart(swiper)` and `onSlideChangeEnd(swiper)` for your logic to control when an element is visible or not.

**Comment by rlech** [comment]
I will give this a try next week. thx for your time to look at this.

**Comment by jlmakes** [comment]
@rlech Feel free to post your results, I don’t mind helping out where I can. I’m not that familiar with Swiper, but it looks like you could manually set `sr.isElemVisible()` to return `true` for the ScrollReveal instance inside the active slide… and `false` for all instances inside inactive slides.
