### ISSUE TITLE
Support nodeList as first reveal argument

### ISSUE THREAD

**Issue by jlmakes** [jlmakes/scrollreveal.js#246]
**Selectors and nodes are already supported...**

```js
// selector
sr.reveal('#chocolate');

// node
var node = document.getElementById('chocolate');
sr.reveal(node);
```

***

### :sparkles: Let’s support NodeList! :sparkles:

```js
// node list
var nodeList = document.querySelectorAll('.chocolates');
sr.reveal(nodeList);
```

# 👍🏾

**Comment by jlmakes** [comment]
Re: @orapouso #20 

I will add support for this into the next release.

**Comment by orapouso** [comment]
:+1:

**Comment by ryanjbonnell** [comment]
When this is added, perhaps a section on [Advanced Selectors][1] could be added to the documentation?

Here's a quick example I came up with:

```javascript
// ScrollReveal using CSS Pseudo-Class Selector:
sr.reveal('h1:not(.no-animation)', {
  distance: '50px',
  origin: 'left'
});
```

This would animate all `h1` elements, except those with the `.no-animation` class using a CSS pseudo-class selector:

```html
<h1>This Will Animate</h1>

<h1 class="no-animation">No Animation</h1>
```

I'm happy to provide more use cases or code examples (CodePen, JSFiddle, etc).

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
