### ISSUE TITLE
 items revealed before the scroll. Why?

### ISSUE THREAD

**Issue by caioavila-arvore** [jlmakes/scrollreveal.js#248]
My itens revealed before the scroll. Why?

```javascript
function revealItens(){
    window.itensHome = new ScrollReveal();

    itensHome.reveal('#how .item', { duration: 700}, 300);
}
```

**Comment by jlmakes** [comment]
- If you use a sequence interval, everything in the sequence will animate as long as any item from the sequence is visible... including items you haven’t yet scrolled into view. _(This is by design_).

- Also some users fix their issues by adding `html, body { height: 100% }` to the CSS.

- Generally speaking, you don't need more than one instance of ScrollReveal—so there's little point in wrapping it in a function called `revealItens()` (which appears to be a typo) that instantiates and calls `reveal` once with a hard-coded configuration.

```js
// you only need this once...
window.sr = ScrollReveal();

// call your reveals as you need them...
sr.reveal('#how .item', { duration: 700 }, 300);
```

**Comment by caioavila-arvore** [comment]
nice! 

`html, body { height: 100% } ` Is the solution!

thanks
