### ISSUE TITLE
Animation presets: scrollreveal.js + Animate.css?

### ISSUE THREAD

**Issue by artfulcat** [jlmakes/scrollreveal.js#249]
Hi.

Can I use scrollreveal.js + Animate.css (https://daneden.github.io/animate.css) ?
It's a landing page. Animate.css has many good animations.
I know about WOW.js, but I think your solution looks better.

I see that I can't or... Any comments "why not? / why will not do it?"
 
P.S. Sorry, for my English.

**Comment by jlmakes** [comment]
Hi @artfulcat, please search existing issues before opening a new one. This has been asked quite a few times already, see #10 #97 #114. (This is good advice for all repos, not just ScrollReveal.) 🐝 

A simple answer is that ScrollReveal _generates its styles_, and is built to be simple and flexible to that end. I suppose you could try using the callbacks to add/remove classes, but you would be better off using a solution developed to work in conjunction with pre-made styles (e.g. WOW.js), or just rolling your own.
