### ISSUE TITLE
page loaded in the middle not start animation in 100% showed place with this object

### ISSUE THREAD

**Issue by pavel81CZ** [jlmakes/scrollreveal.js#252]
Hello, I found one issue. When Is page standard loaded, animation work perfect, but when is page scrolled to other place (in the middle page), where is showed animated content and then is page reloaded with F5 (or browser button), then animated content isn't show until page is scrolled to any direction, although is place with animated object 100% showed.

Is any way to solve this problem myself, some bad parameter or any function which I overlooked?

Thanks for help.
Pavel

My initialization code is:
```js
if(typeof ScrollReveal != 'undefined') {
    window.sr = new ScrollReveal({mobile:false,reset:false,viewFactor:0.1,viewOffset: {top:0, right:0, bottom:0, left:0 }});
    sr.reveal(".sloupce .col-1-3 h2, .sloupce2 .col-1-4 h2, .sp_logo", {origin: "left", distance: "5vw", duration: 900, delay: 5, scale: 1});//10
    sr.reveal("#paticka", {origin: "bottom", distance: "5vw", duration: 900, delay: 0, scale: 1});
    sr.reveal("h1", {origin: "left", distance: "5vw", duration: 900, delay: 500, scale: 1});
    sr.reveal(".sloupce .module .obsah img.thumb, .sloupce2 .module .obsah img.thumb", {reset: false, rotate: {x: 65}, duration: 900, delay: 10});//50
}
```

**Comment by jlmakes** [comment]
@pavel81CZ It sounds like your functions aren’t running after the DOM has completed loading. Are you using `sr.reveal()` at the end of the page?

_For Example:_
```html
<html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <p>Some content.</p>
        <p>Some other content.</p>

        <script>
            window.sr = ScrollReveal();
            sr.reveal('.foo');
        </script>
   </body>
</html>
```

Or if you using jQuery, something like:

```js
/* wait for document ready
$(document).ready(function(){

but use shorthand syntax... */
$(function(){
    window.sr = ScrollReveal();
    sr.reveal('.foo');
});
```
Both will allow your content to be loaded before running any scripts.

Also, I recommend reviewing the defaults—you set these properties below:
```js
reset: false,
viewOffset: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0
}
```
But they are already the starting defaults, there’s no need to redefine them when you instantiate ScrollReveal—you could just use:
```js
window.sr = ScrollReveal({ mobile: false, viewFactor: 0.1 });
