### ISSUE TITLE
Its not working with modernizr.js

### ISSUE THREAD

**Issue by SaurabhRSonawane** [jlmakes/scrollreveal.js#254]
I am trying to use scrollreveal.js for my new website, but whenever I use modernizer.js, only first element gets reveal and after that each element get disappear. I don't know I am doing it right or wrong but it doesn't work.

**Here is my sample code:**

```html
<head>
    <link rel="stylesheet" href="assets/css/style.css">
    <script src="assets/js/modernizr-custom.js"></script>
</head>

<h3 class="foo">Sample Heading</h3>
<a class="bttn bttn-blue bttn-med bttn75 bttn-scale margin-top50 foo">Say Hello</a>

<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.1.4/scrollreveal.min.js"></script>
<script>
    window.sr = ScrollReveal();
    sr.reveal('.foo');
</script>
```

**Comment by jlmakes** [comment]
@SaurabhRSonawane Are there any messages in the console?

**Comment by SaurabhRSonawane** [comment]
@jlmakes No, I didn't see any message in a console..

**Comment by jlmakes** [comment]
@SaurabhRSonawane I think the best bet is a code demo, so I can help you troubleshoot. Do you have [JSBin](http://jsbin.com) or the site uploaded somewhere?

**Comment by jlmakes** [comment]
@SaurabhRSonawane I think the best bet is a code demo, so I can help you troubleshoot. Do you have [JSBin](http://jsbin.com) or the site uploaded somewhere?

**Comment by jlmakes** [comment]
@SaurabhRSonawane Here is a [Demo with Modernizr and ScrollReveal](http://jsbin.com/huzowi/edit?html,js,output). I’m not sure what problem you’re having, feel free to share more about your situation.

**Comment by SaurabhRSonawane** [comment]
Thanks @jlmakes for your demo from JSBin. I tried to implement that way, But I found the issue in my page that all blocks below the fold content are revealing at the same time as above the fold content that's why its not showing reveal effect. 
I tried to add some more blocks in your demo but after scrolling you will found that they are already revealed. I dont know what's the issue and how to implement scrollreveal actually..?

**Comment by jlmakes** [comment]
@SaurabhRSonawane I was using the interval parameter for sequences.

_for example:_
```js
sr.reveal('.selector', 150)
```

This will reveal all elements in a set, one after another, with 150ms in between. I’ve updated the demo to not use this, please check the link again. 🙇

**Comment by SaurabhRSonawane** [comment]
Thanks @jlmakes for your quick reply.
I have uploaded the page where I am facing a problem..please do visit and tell me how should I implement Scrollreveal.js
[http://webtest.ieyze.com/block/Content_Blocks.html](url)
Its not on jsbin but you can check its source code..

**Comment by jlmakes** [comment]
@SaurabhRSonawane When I type `sr` in the console, it says it’s `undefined`. When I type `ScrollReveal` in the console, it says it’s `undefined`. Not sure what you’ve got going on, but I can’t help you much like this.

Also, you’re using a "smooth scrolling" library—that could _easily_ be causing a problem if it’s interfering with normal scroll events. (I took a cursory look at the source, and it looks like it is disabling the default event handling for keyboard and mouse based scrolling.)

I’m going to guess the smooth scrolling is the problem. Good luck!
