### ISSUE TITLE
Scrollreveal issue with lazyloading

### ISSUE THREAD

**Issue by jithujose** [jlmakes/scrollreveal.js#255]
Hi, 
Scroll reveal is not working properly when used with a lazyloader like this one here: [aFarkas/lazysizes](https://github.com/aFarkas/lazysizes).
The problem is that all elements are getting revealed immediately and not on scroll when lazysizes is active.

OS: Ubuntu 15.04
Scrollreveal:  v3.1.4
Lazysizes: v1.5.0

Any hints?

Thanks!

**Comment by jlmakes** [comment]
According to the [Lazysizes documentation on JS API Events](https://github.com/aFarkas/lazysizes#js-api---events), you can listen to when elements are loaded but not yet shown—which looks like the time in the lifecycle to call 3rd party libraries.

_For Example:_
```js
document.addEventListener('lazybeforeunveil', function (event) {
  var element = e.target
  sr.reveal(element)
})
```

There’s a whole section on creating reveals (or what Lazysizes calls "unveils") using `.lazyload` and `.lazyloaded` classes, but it sounds like can ignore most of that.

**Comment by jithujose** [comment]
Ok, I tried the lazybeforeunveil event but unfortunately it doesn't help.

**First try:**
```
// lazysizes initialized
var sr = ScrollReveal();
sr.reveal('.fadein');

// When loading items via ajax
ajax(function(resp) {
    $(container).append(resp.html);
    sr.sync();
});

```

**Second try**
```
// lazysizes initialized
var sr = ScrollReveal();

document.addEventListener('lazybeforeunveil', function (e) {
    var fadein = $(e.target).parents('.fadein').first();
    if (fadein.length) {
        sr.reveal(fadein.get(0));
    }
});

```

I still get everything revealed immediately on page refresh and with ajax requests.

**Comment by jithujose** [comment]
It's working now, but I don't understand what has changed actually...

**Comment by jlmakes** [comment]
@jithujose Haha, welcome to development.

### It’s not working...
![imgres](https://cloud.githubusercontent.com/assets/2044842/15257082/f4af2366-1944-11e6-862c-6539eb08fe72.jpg)

### It’s working...
![imgres](https://cloud.githubusercontent.com/assets/2044842/15257082/f4af2366-1944-11e6-862c-6539eb08fe72.jpg)
