### ISSUE TITLE
How to use ScrollReveal with Angular2

### ISSUE THREAD

**Issue by vascogaspar** [jlmakes/scrollreveal.js#258]
Hello. I'm trying to use ScrollReveal in my Angular2 project (version 2.0.0-rc.1) and I'm struggling to make it all work together.

What I have right now is:

in my index.html, I'm importing the library directly
`<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.1.4/scrollreveal.min.js"></script>`

then in my component I have this:

```js
declare var ScrollReveal: any;

export class Foo  {
  ...
  ngAfterViewInit() {
    window.sr = ScrollReveal();
    window.sr.reveal('.foo');
  }
  ...
}
```

and finally on my component template html I have an element with the `foo` class.

My DOM node looks like this when it renders, but nothing else is actually working
```html
<div class="foo" data-sr-id="1" style="; visibility: visible;  -webkit-transform: translateY(20px) scale(0.9); opacity: 0;transform: translateY(20px) scale(0.9); opacity: 0;">...</div>
```

Do you have any idea on how to solve this?
Thanks!

**Comment by jlmakes** [comment]
I don’t have much experience with Angular 2, but I would be interested to develop documentation for using ScrollReveal with it. Did you make any progress?

I want to make sure this gets covered in the upcoming documentation improvements.
