### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by Hugheth** [jlmakes/scrollreveal.js#260]
Hi there,

This error above seems to be being thrown if and only if the scroll reveal method is called on a dom element when the page tab is not focused (e.g. you load the page and then click on a different browser tab/window)

`sr.reveal( '.textElement', { delay: 100 } );`

The textElement is available at the point this method is called.

Mac OSX, Chrome latest, library version 3.0.6

**Comment by jlmakes** [comment]
I wasn’t able to recreate this. Did you make any progress?

**Comment by jlmakes** [comment]
I load the demo page and click away immediately — no reveals are triggered until I focus the tab, and there are no error messages when I do.

What am I missing?

**Comment by rista404** [comment]
Hey @jlmakes, sorry for a delayed response. 

I was getting the same error message but with use of React. I've put the init code for ScrollReveal inside a `componentDidMount` lifecycle hook, and (for some reason) at that point the elements weren't rendered yet. I've fixed it at the end, it had nothing to do with the scrollreveal lib. 😄 

So I guess it's not only when you switch the tab right away (haven't experienced that), it has to do with the element (somehow) not being defined. 

Ping me if you need anything else :)
Hope that helps.

**Comment by jlmakes** [comment]
Thanks @rista404, I think I’ll want to put together some "Using ScrollReveal with React" for the documentation at some point.

I’ll close this issue until something else arises.

# 👍🏾

**Comment by AdamNowaczyk** [comment]
I'm getting same error:

scrollreveal.js:328 Uncaught TypeError: Cannot read property 'config' of undefined

This only happens if I'll include Google Maps in iframe (copy paste from Google docs, no custom chagnes).

**Comment by jlmakes** [comment]
@AdamNowaczyk which version of ScrollReveal?

**Comment by sushicodeur** [comment]
I also have the same error. I can give you an html page with all of its dependency that reproduce the error. Or this fiddle : https://jsfiddle.net/sushicodeur/xfp8xyLr/

**Comment by sushicodeur** [comment]
Ok ! Got it ! 

In my markup I copy-pasted the entry content from a browser, thus the scrollreveal elements had data-sr-id already set.

When calling sr.reveal( '.textElement' ); .textElement cannot have data-sr-id attributes.
