### ISSUE TITLE
css3 transform property not working on scrollReveal element

### ISSUE THREAD

**Issue by nunaram** [jlmakes/scrollreveal.js#265]
My Code look Like this.
``` css
    /*  CSS STYLE   */
    <style>
    a:hover {
    transform: scale(1.2) rotate(360deg);
    }
    </style>
```
``` html
    <!-- HTML MARKUP -->
    <div id="social">
    <a href="https://www.facebook.com/"><i class="fa fa-facebook-f"></i></a> 
    <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a> 
    <a href="https://plus.google.com/"><i class="fa fa-google-plus"></i></a>
    </div>
```
``` javascript
   //  SCROLL REVEAL JS 
<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.1.4/scrollreveal.min.js"></script>
<script>
      window.sr = ScrollReveal();
     sr.reveal('#social a', { duration: 2000, distance: '150px', reset: true },100);
</script>
```
ScrollReveal is working perfect but, whenever I mouse over on social icon it's transform property is not working. I want to rotate and scale icon on hover event. Maybe scrollReveal is resetting my defined css property. 

Any help will be appreciated.

**Comment by jlmakes** [comment]
ScrollReveal uses CSS transforms during the reveal effect, so the inline styles generated by ScrollReveal are most likely overriding your anchor tag’s transform on hover.

I think the simplest solution is to just wrap the links in another element, so that ScrollReveal has something else to grab on to. For example:

``` css
a:hover {
    transform: scale(1.2) rotate(360deg);
}
```
``` html
<div id="social">
    <div class="iconlink">
        <a href="https://www.facebook.com/"><i class="fa fa-facebook-f"></i></a> 
    </div>
    <div class="iconlink">
        <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a> 
    </div>
    <div class="iconlink">
        <a href="https://plus.google.com/"><i class="fa fa-google-plus"></i></a>
    </div>
</div>
```
``` javascript
window.sr = ScrollReveal()
sr.reveal('.iconlink', { duration: 2000, distance: '150px', reset: true }, 100)
```

**Comment by nunaram** [comment]
Wow that's a good idea. It's working now perfect. Thank you very much.

**Comment by jlmakes** [comment]
@nunaram Any update?

**Comment by nunaram** [comment]
Wow that's a good idea. Now it's working fine. Thank you very much.

**Comment by Zeboch** [comment]
Better solution should be to look at the style applied on element and merge transform properties with srollreveal needed ones.

Using this [very good] JS plugin shouldn't be an argument to make "not good" markup ;)

**Comment by jlmakes** [comment]
I agree @Zeboch, and that’s already how things work for CSS transitions and opacity. Feature request #251 to extend support to preserve CSS transforms is already on the roadmap.

For the time being, creating a wrapping element to preserve CSS transforms is the simplest solution.

**Comment by Anathapindikap** [comment]
thx, 8 years have passed and you still helped another unfortunate soul
