### ISSUE TITLE
How to disable ScrollReveal.js on ie9

### ISSUE THREAD

**Issue by SaurabhRSonawane** [jlmakes/scrollreveal.js#266]
It gives some jerk to appearing DIV's during on-Scroll in **internet explorer 9**.
Is there any method or trick to disable **ScrollReveal.js** in **ie9 and earlier browsers**

**Comment by jlmakes** [comment]
What version of ScrollReveal are you using?

ScrollReveal checks CSS Transform and CSS Transition support… which Internet Explorer 9 and earlier browsers will fail. ScrollReveal shouldn’t be doing much of anything.

_Example:_

```js
/**
 * Check if client supports CSS Transform and CSS Transition.
 * @return {boolean}
 */
ScrollReveal.prototype.isSupported = function () {
    var style = document.documentElement.style
    return 'WebkitTransition' in style && 'WebkitTransform' in style
        || 'transition' in style && 'transform' in style
}
```

**Comment by SaurabhRSonawane** [comment]
I am using a legacy version of scrollReveal.js... (it is well documented and easy to implement that's why I tried to implement it)

**Comment by jlmakes** [comment]
In that case, I can’t offer much support. This is a valid request, which is exactly why it was addressed in future versions of ScrollReveal. It’s up to you to detect IE9, and only instantiate ScrollReveal when is appropriate.

>I tried to implement a new version and it is not working like I want, so I preferred legacy version over new one.

Version 3 does everything, _and plenty more_ than legacy versions. The main difference is you don’t use HTML attributes to control your animations, you use JavaScript— which means cleaner markup. What problem were you having?

**Comment by SaurabhRSonawane** [comment]
Thanks for your quick reply :-)

I have implemented a latest version of **ScrollReveal.js** and its working superbly fine. I just found the bug in my css stylesheet that, I have **set main class to 100vh height** that's why all elements, which are above the fold content and below the fold content gets revealed at the same time. After removing 100vh property, its working fine on scroll.

I just wanted to ask you that, as per the documentation I tried to implement **Sequenced Animations** but when I apply Sequenced Animations, all the elements (above and below the fold) get reveal at the same time, so scroll effect doesn't seem to work there. So, I tried to implement **Sequenced Animations** differently for each section, and its working.

like,
```javascript
window.sr = ScrollReveal();
sr.reveal('.foo',{duration: 700,delay : 300,distance: '50px',viewFactor  : 0.5});
sr.reveal('.content-block-1 .foo',100);
sr.reveal('.content-block-4 .foo',150);
```

but my question is how to implement **Sequenced Animations** for all the divisions on the same page?
Can we do this liks,
```javascript
sr.reveal('.content-block-1 .foo,.content-block-4 .foo',150);
```

**Comment by jlmakes** [comment]
Glad you got the new version working for you!

If we are to take this example expression:
```js
sr.reveal('.selector-1, .selector-2', 200);
```
This would take all elements found with `.selector-1` and `.selector-2` and group them into a sequence. That means that anytime any element with `.selector-1` or `.selector-2` becomes visible, _the entire group will reveal sequentially (as found in the DOM), with 200ms between each reveal._

>**Note:** It’s a little counter-intuitive because it means elements that aren’t visible can be revealed, but trust me when I say — this is far simpler than alternative behaviors. (I spent weeks on the logic.)

So in other words...

#### You can’t define multiple sequences with one expression, because they will just be grouped into the same sequence.

In order to create separate sequences (even if they share the same configuration and interval), you must use separate expressions:

```js
sr.reveal('.selector-1', 200);
sr.reveal('.selector-2', 200);
```

Does that help?

**Comment by SaurabhRSonawane** [comment]
Means, I want to do like this only,
```javascript
sr.reveal('.content-block-1 .foo',100);
sr.reveal('.content-block-2 .foo',150);
```
right..?

No problem. By the way, thanks for this ultimate plugin. Thank you very much for your support :-)

**Comment by jlmakes** [comment]
Yep, looks good. Glad to help.
