### ISSUE TITLE
requestAnimationFrame and older browsers

### ISSUE THREAD

**Issue by OscarBarrett** [jlmakes/scrollreveal.js#267]
Older browsers such as the Android Browser <= 4.3 [don't support requestAnimationFrame](http://caniuse.com/#feat=requestanimationframe) and throw `undefined is not a function` because of https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L926 - there is no fallback when there is no requestAnimationFrame available.

A polyfill such as [this one](https://github.com/cagosta/requestAnimationFrame) could be used, or a simple fallback such as

    function(f) { f() }

**Comment by jlmakes** [comment]
I had a polyfill in earlier versions, but it seemed that all browsers that supported CSS transforms and transitions also supported request animation frame — but it was an oversight on my part. I don’t mind adding those few lines of code back in.

Thanks @OscarBarrett
