### ISSUE TITLE
New Callbacks: `beforeReveal` and `beforeReset`

### ISSUE THREAD

**Issue by ivangretsky** [jlmakes/scrollreveal.js#273]
I need to start some js (CountUp.js) on event that happens when the element starts revealing, not when it is revealed. So it is being revealed already being animated. Can't find a callback for that. Am I missing it? If there is not one, is it possible to add it?

**Comment by jlmakes** [comment]
You are correct, the two callbacks are `afterReveal` and `afterReset`, there is currently no such thing as `beforeReveal` and `beforeReset`.

That said, it shouldn’t be too difficult to add those in…

`afterReveal` and `afterReset` use timeouts to correctly time their execution, but `beforeReveal` and `afterReveal` would simply need to be triggered appropriately [inside the `_animate()` method](https://github.com/jlmakes/scrollreveal.js/blob/master/src/scrollreveal.js#L521).

If you want to take a stab at it in a fork of ScrollReveal for your project, I can offer guidance. For now, I will icebox this feature request for a future release.

**Comment by jlmakes** [comment]
@ivangretsky Thanks for the request, it’s now live in `3.3.0`.

_Example:_

```js
// Let’s see all 4 together now...
sr.reveal('.foo', {
  beforeReveal: (el) => console.log('Reveal started...'),
  afterReveal: (el) => console.log('Reveal complete.'),
  beforeReset: (el) => console.log('Reset triggered...'),
  afterReset: (el) => console.log('Reset complete.')
})
```
