### ISSUE TITLE
Dom Element Not Showing

### ISSUE THREAD

**Issue by johnthachil** [jlmakes/scrollreveal.js#275]
```html
<h1 class="fadeIsn" >Pick Seat</h1>

<script type="text/javascript">
  window.sr = ScrollReveal();
  sr.reveal('.fadeIsn');
</script>

```
my dom element with class fadeIsn is hidden when do this.

**Comment by jlmakes** [comment]
ScrollReveal hides all elements before revealing them, but if they aren't revealing you have another problem. I’ll need a little more information about your project if I am to help you debug.

**Comment by johnthachil** [comment]
**fixed needed to change container to div **
