### ISSUE TITLE
Don't reveal without scroll

### ISSUE THREAD

**Issue by thiagosyncmob** [jlmakes/scrollreveal.js#276]
Hi

Is it possible to disable reveal for those items that don't need scroll to be visible (considering different screen sizes)? In other words, I just want to reveal when I scroll, not at page startup.

Thank you

**Comment by jlmakes** [comment]
Ah, I believe I understand @thiagosyncmob

First, by calling `sr.reveal()` with a `duration: 0`, all visible elements will be immediately visible on load.

Second, we pass an `afterReveal` callback, that calls `sr.reveal()` _again_ on the same element set — but this time with the desired reveal animation duration. This will overwrite the previous `duration: 0`, achieving the effect you’re after.

### I made you a demo → [Live on JSBin](http://jsbin.com/mulokeg/edit?html,js,output)

_Example:_
```js
sr.reveal('.box', {
  duration: 0,
  afterReveal: function () {
    sr.reveal('.box', { duration: 500 })
  }
})
```

**Comment by jlmakes** [comment]
Great question by the way @thiagosyncmob 👍🏾

**Comment by thiagosyncmob** [comment]
Worked perfectly!

Thank you so much @jlmakes
