### ISSUE TITLE
Replaying reveals?

### ISSUE THREAD

**Issue by anetk** [jlmakes/scrollreveal.js#277]
Hey! I don't have any issue yet, just wondering how to achieve something.
So I want to do something like this here:
https://onedesigncompany.com/approach -- the SVG drawing but as you can see, the animation appears only when you are on that section if you scroll up and down animation never stops.
Does that make sense? Basically I want when I go from the bottom to the top animation to be shown again.

**Comment by jlmakes** [comment]
Have you tried using the `reset` property?

```js
sr.reveal('foo', { reset: true });
```

**Comment by anetk** [comment]
So if I want animate based on scroll position I just use reset? or there is another way to specify position?

**Comment by jlmakes** [comment]
>"So if I want animate based on scroll position I just use reset?"

No. ScrollReveal does not animate based on scroll position; it animates based on element visibility. I can’t recommend another solution from experience, but directly from the Scrollmagic site:

>ScrollMagic helps you to easily react to the user's current scroll position.

I would start there.

**Comment by anetk** [comment]
THANKS!
