### ISSUE TITLE
Uncaught TypeError using Bower and Wordpress

### ISSUE THREAD

**Issue by anoopd** [jlmakes/scrollreveal.js#278]
I just tried to include ScrollReveal to one of my Wordpress installs, and it is giving me Uncaught TypeError : (intermediate value)(intermediate value)(intermediate value) scrollreveal.js:850(...) is not a function.

Installed using bower and latest chrome stable, the error is with:
```js
window.ScrollReveal = ScrollReveal
```

is there anything wrong on my part?  Any conflict with JQMigrate?

**Comment by jlmakes** [comment]
Hey @anoopd, that’s odd. I’m not sure how Wordpress or jQMigrate would cause a runtime error in this situation. I just ran a test installation:

- `md test && cd test`
- `bower install scrollreveal` (version 3.3.1)
- `touch index.html`
- Added `<script src="./bower_components/scrollreveal/dist/scrollreveal.js"></script>`
- Added `<script>window.sr = ScrollReveal()</script>`
- Loaded it up in Chrome 51
- _No errors_

**Comment by anoopd** [comment]
Thank you for the fast and precise reply . I was using it with a theme that already have a bower.json file (Roots Sage ) and which adds scrollreveal as its dependency . I was able to rectify the error by overriding it to min version in my bower.json file .


   `
"overrides": {`

       "scrollreveal" :{
 
            "main":["./bower_components/scrollreveal/dist/scrollreveal.min.js"],
             "dependencies":{}
      }
    }`

**Comment by jlmakes** [comment]
>"I tried overriding the minified version but it just stopped loading the script"

Some themes use outdated versions of ScrollReveal, which can can be quite confusing. For example, if you manually installed a more recent version—it’s possible the theme’s use of ScrollReveal will break.

I actually encountered a user than had the _very first release_ (from almost 3 years ago) installed on the Wordpress theme he purchased.

>"I am not sure what caused the error but other than that the script is working"

So, it is working?

**Comment by anoopd** [comment]
Hi Jlmakes
                     Thank you for the reply  ...... It is not a premium theme with scroll reveal installed , i am making a theme , using the sage roots framework , i installed scrollreveal using bower , enqueued the script and then found the error i mentioned  . 

   Yes though the console is still showing the error the script is working .....

One more thing off topic , is there a chance to animate svg's using scrollreveal ? Using a function ?

**Comment by jlmakes** [comment]
ScrollReveal allows the `new` keyword to be omitted, but there’s absolutely nothing wrong with using it.

```js
window.sr = new ScrollReveal();
```

I’m not sure what would be causing the console error, seeing as I tested bower installation yesterday.

**Comment by anoopd** [comment]
I just did some small research on the error and found this . Please have a look 

http://stackoverflow.com/a/25412298/742648

**Comment by jlmakes** [comment]
Can you do me a favor, and add a semi-colon at the end of your ScrollReveal script to see if this fixes the problem? If so, I will patch this right away.

```diff
   if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {
     define(function () {
       return ScrollReveal
     })
   } else if (typeof module !== 'undefined' && module.exports) {
     module.exports = ScrollReveal
   } else {
     window.ScrollReveal = ScrollReveal
   }
-}())
+})();
```

**Comment by anoopd** [comment]
Tried it , but in vain  :(
![screen shot 2016-08-05 at 8 59 59 pm](https://cloud.githubusercontent.com/assets/925418/17441653/b3d1ef66-5b4f-11e6-83f5-72f325c90d41.png)

![screen shot 2016-08-05 at 8 59 47 pm](https://cloud.githubusercontent.com/assets/925418/17441670/ccd77792-5b4f-11e6-8b0b-94a9afa2f37f.png)

**Comment by jlmakes** [comment]
Everything I‘ve found seems to point to missing semi-colons at the beginning and end of libraries, creating errors when they are used together.

From your testing, even when ScrollReveal has a semi-colon at the beginning and end, the error still shows. Not sure what to suggest 😕

Have you tried removing other Javascript libraries to see if the error goes away?

**Comment by anoopd** [comment]
Hi
      Thanks for the changes you made  ........  The error is not there now  .........

**Comment by anoopd** [comment]
Can you please share the changes you made ?

**Comment by jlmakes** [comment]
I haven‘t made any changes 😅

**Comment by anoopd** [comment]
Real Wonder  ...... !! Anyway thank you for the efforts behind scrollreveal and making it open source  ......

**Comment by jonathanjanssens** [comment]
I have just had this exact same issue, working with Sage Wordpress theme, installed scrollreveal with bower and compiling with gulp. Applying the semicolon patch you mentioned in https://github.com/jlmakes/scrollreveal/issues/278#issuecomment-237826969 did fix the issue for me:

![screen shot 2017-02-08 at 10 41 31](https://cloud.githubusercontent.com/assets/3079607/22734087/604ced70-edec-11e6-9852-f3925158832e.png)
![screen shot 2017-02-08 at 10 41 13](https://cloud.githubusercontent.com/assets/3079607/22734088/604de428-edec-11e6-9eaf-730d274eec0b.png)

**Comment by jlmakes** [comment]
Are you @jonathanjanssens @anoopd both working with this https://roots.io/sage/?

If so, I'll reach out the developer to see if we can get this fix baked in, or perhaps update what version of ScrollReveal is used. (Version 4 is in beta!)

**Comment by anoopd** [comment]
Hi Jlmakes , 
                         Nope Sage is a base theme framework and  scrollreveal was added for a specific project ......
