### ISSUE TITLE
Scrollreveal is not working inside slider

### ISSUE THREAD

**Issue by horace524** [jlmakes/scrollreveal.js#279]
Part of my webpage is constructed with Slick slider with 2 slides for in-page navigation, however the scrollreveal only works in the first slide. In the 2nd slide the animated elements are not showing, and no animation. I am using chrome and safari and they both didn't work. Any help please?

Thank you in advance!

**Comment by jlmakes** [comment]
Any time you combine a library that changes either scroll behavior, or element visibility, you increase the likelihood of odd/unexpected results with ScrollReveal which depends on both.

Describing the problem is not enough to help troubleshoot, can you please provide code samples?

**Comment by horace524** [comment]
Sorry I am still new in web development so please bear with me!

Below is the structure of my code, scrollreveal work well in scroll_1 but not for scroll2.

```
<div class="slider">
	<div>
		<div id="scroll_1">
			Scroll 1
		</div>
	</div>
	<div>
		<div id="scroll_2">
			Scroll 2
		</div>
	</div>
</div>


<script>
	$('.slider').slick();

	window.sr = ScrollReveal();
	sr.reveal('#scroll_1');
	sr.reveal('#scroll_2');
</script>
```

**Comment by jlmakes** [comment]
No worries @horace524 👍🏾

### Diagnosing The Problem

I took a look at the [Slick slider plug-in](http://kenwheeler.github.io/slick/), and it’s using CSS Transform to change the position of the slider. With the ScrollReveal currently works, this will break "out of the box" compatibility.

Using a CSS Transform (e.g. `transform: translateX(500px)`) changes the displayed position of an element, but the element’s position (as far as ScrollReveal is concerned) does not factor in the CSS Transform.

*So in other words, even if your second slide is translated into view using CSS… it will still be considered out of view under the hood.*

### Getting It Working?

It would require changes to the ScrollReveal source, and using Slick’s events API… but that’s not an ideal solution, let alone for a beginner.

However, I took a look at how the plug-in works, and `.slick-active` is applied to each slide that is currently visible. You should be able to hook into this behavior of the Slick plug-in to create your own simple reveal effect.

_Example CSS:_

```css
.slick-slide {
  transition: opacity 0.3s ease-in-out 0.2s;
  opacity: 0;
}
.slick-active {
  opacity: 1
}
```

I used a duration of `0.3s`, which is pretty fast—but with a delay of `0.2s` to give the slider time to move before any opacity changes occur. This is of course up to you to decide what works best.

Hope this helps!

**Comment by d-denver** [comment]
You need to make changes in _getOffset function in scrollreveal.js:
`function _getOffset (domEl) {
    var offsetTop = 0
    var offsetLeft = 0

      // Grab the element’s dimensions.
    var offsetHeight = domEl.offsetHeight
    var offsetWidth = domEl.offsetWidth
    
    // Now calculate the distance between the element and its parent, then
    // again for the parent to its parent, and again etc... until we have the
    // total distance of the element to the document’s top and left origin.
    do {
      if (!isNaN(domEl.offsetTop)) {
        offsetTop += domEl.offsetTop
      }
      if (!isNaN(domEl.offsetLeft)) {
        offsetLeft += domEl.offsetLeft
      }
      
      //++CHANGES
      if(domEl) {
        var translateX = _getTransformX($(domEl));
        offsetLeft+=translateX;
      }
      //--CHANGES

      domEl = domEl.offsetParent; 
    } while (domEl)

    return {
      top: offsetTop,
      left: offsetLeft,
      height: offsetHeight,
      width: offsetWidth
    }
  }`

And new function _getTransformX:
`function _getTransformX(domEl) {
      
    var transformMatrix = domEl.css("-webkit-transform") ||
                          domEl.css("-moz-transform")    ||
                          domEl.css("-ms-transform")     ||
                          domEl.css("-o-transform")      ||
                          domEl.css("transform");
    var matrix = transformMatrix.replace(/[^0-9\-.,]/g, '').split(',');
    var x = parseInt(matrix[12] || matrix[4]);//translate x
    if(isNaN(x)) {
        return 0;
    }
    return x;
  }`

Remark: in my code I use jQuery, whereas scrollreveal.js use pure Javascript.

**Comment by afalchi82** [comment]
I'm going with this hacky workaround:

```javascript
window.addEventListener('load', function () {  
    setTimeout( () => {
      $(window).resize( function () {
        scrollRevealInitFunction();
      }).resize();
    }, 100);
  });
```
