### ISSUE TITLE
Microsoft Edge 25 can't load page with high number of reveal elements

### ISSUE THREAD

**Issue by JanSchmidhofer** [jlmakes/scrollreveal.js#281]
Hello,

I have a page with 62 elements to be animated by scrollreveal. If i open the page, Microsoft Edge tells me, that the page could not be loaded (Beim Laden dieser Seite ist ein Problem aufgetreten / while loading this page a problem occured). The Version of Edge is:

Microsoft Edge 25.10586.0.0 (Microsoft Edge html 13.10586)

But the page works fine in Microsoft Edge 38.14393.0.0 (Microsoft EdgeHTML 14.14393) and in all other browsers (Chrome, Firefox, Safari, Opera, iOS 8 and 9, Android 4.2.2 to 6). If i reduce the number of elements to be animated, the page loads fine in Edge 25.

Is this a known bug and is there a way to fix this for this version of Edge ? Or is it just a bug in Edge 25, which was the first version delivered with windows 10?

**Comment by jlmakes** [comment]
Hey @JanSchmidhofer 

I did _not_ know about this bug, so thanks for bringing this to my attention. I’m not sure what would be causing the problem, but is there maybe a log file I could take a look at? It sounds like something specific to version 25, but if I can add support for that browser, I’ll gladly dig into the error.

**Comment by JanSchmidhofer** [comment]
i also think its a browser bug, ive reduced the number of elements to be animated and now it works.
