### ISSUE TITLE
Smooth - problem in Firefox

### ISSUE THREAD

**Issue by kriss145** [jlmakes/scrollreveal.js#284]
Hi,

ScrollReveal version: 3.1.4
Firefox v48.0
OS X El Capitan v10.11.6

In firefox I have a problem with good work ScrollReveal. Is not a smooth.
In Chrome, Safari, even in IE10 is all fine.

Could you help me find solution for this?

Thanks

**Comment by jlmakes** [comment]
I just loaded up the ScrollReveal demo in Firefox 48, and everything looks good.

Can you provide either a screen recording, or a link to the page you're having a problem with?
