### ISSUE TITLE
Invalid CSS Transition (NaNs)

### ISSUE THREAD

**Issue by AdsonCicilioti** [jlmakes/scrollreveal.js#287]
I am loading the scrollReveal.min.js concatenate via uglify grunt and activating the elements at the end of the tag `</ body>` as follows:

```html
<script type="text/javascript">
	var config = {
		viewFactor: 0.3,
		delay: 'onload',
		duration: 800,
		reset: false
	}
	window.sr = new ScrollReveal(config);
	sr.reveal( '.sr-r', { origin: 'right' }, 50 );
	sr.reveal( '.sr-l', { origin: 'left' }, 50 );
	sr.reveal( '.sr-t', { origin: 'top' }, 50 );
	sr.reveal( '.sr-b', { origin: 'bottom' }, 50 );

</script>
```
Everything seems to work fine except the smoothness of the animations. When checking the CSS attributes incorporated into the elements, I came across invalid values (NaNs) in the transition property.

![capturar](https://cloud.githubusercontent.com/assets/6278398/18110760/6cb30534-6ef0-11e6-9731-9fe41fea06b7.PNG)

How solve this?? I no have a idea! :(

- OS: Win 10
- Browser: All possible - latest versions
- ScrollReveal: Latest

**Comment by jlmakes** [comment]
I've quickly tested ScrollReveal v3.3.1 on Chrome and MS Edge (Win 10) and I'm not seeing this issue. I put together this [JS Bin Demo](http://jsbin.com/lorowa/edit?html,css,output) and everything behaves as expected.

**Comment by AdsonCicilioti** [comment]
Thx for Reply @jlmakes,
My case exactly follow this example: [JSBin](http://jsbin.com/kebihel/edit?html,js,output)
It seems the problem is to add the variable `config` and then add even more distinct options. When I remove the variable `config` everything works pretty well, but I'm without my global settings.

Am I doing wrong?

**Comment by jlmakes** [comment]
Thank you for the live code sample demonstrating the problem @AdsonCicilioti 

Looking through the `sr.store`, it seems that all the values are correctly being assigned to the elements... and even the correct `config.easing` makes it into the `_generateTransition()` method. The data _is_ being passed around, but something is going wrong with the `config.duration`.

I'll dig into this tomorrow and get back to you.

**Comment by jlmakes** [comment]
@AdsonCicilioti I figured it out :wink: 

In your config, you're using `delay: 'onload'`, but you meant to use `useDelay: 'onload'`. The `config.delay` property is used to define how long the delay is, whereas `config.useDelay` defines when/if delay is used.

**Comment by AdsonCicilioti** [comment]
Nice!! Thanks @jlmakes
