### ISSUE TITLE
If Parent element is absolute, it screws up with the Scrollreveal

### ISSUE THREAD

**Issue by amanjareck** [jlmakes/scrollreveal.js#288]
Please find the JsFiddle Example

https://jsfiddle.net/ozx9soux/

**Comment by amanjareck** [comment]
Please find the JsFiddle Example

https://jsfiddle.net/ozx9soux/

**Comment by jlmakes** [comment]
Actually, ScrollReveal handles `position: absolute` just fine. The problem here is that you've used a custom container, which needs to be specified in the configuration.

https://jsfiddle.net/ozx9soux/4/
