### ISSUE TITLE
not work in Joomla ?

### ISSUE THREAD

**Issue by PDX1337** [jlmakes/scrollreveal.js#295]
- Ubuntu, Apache2, php7, jquery 2.10
- latest firefox
- latest scrollreveal version
- joomla 3,6,2

Hi,
i load the my Joomla template in blocks

so head.php

```php
<?php $this->addScript(T3_TEMPLATE_URL.'/js/scrollreveal.min.js'); ?>
<script>
  window.sr = new ScrollReveal();

  // Add class to <html> if ScrollReveal is supported
  if (sr.isSupported()) {
    document.documentElement.classList.add('sr');
  }
```

layout.php

```php
	<?php $this->loadBlock('spotlight-14') ?>
	<?php $this->loadBlock('spotlight-15') ?>
	<?php $this->loadBlock('spotlight-16') ?>
	<?php $this->loadBlock('spotlight-17') ?>
	<?php $this->loadBlock('spotlight-18') ?>
	<?php $this->loadBlock('spotlight-19') ?>
	<?php $this->loadBlock('spotlight-20') ?>
	
	<?php $this->loadBlock('footer') ?>
	<?php $this->loadBlock('spotlight-21') ?>
</div>

   <script>
      sr.reveal('.fooReveal', { container: '.fooContainer' });
    </script>
</body>
</html>

```
template.css

` .sr .fooReveal { visibility: hidden; }`

hope you can help 

Regards
PDX

Thanks!

**Comment by jlmakes** [comment]
You call `sr.reveal()` on the elements with the `.fooReveal` class, but I don't see any; you declared a custom container with the class `.fooContainer` but I don't see it -- Plus, it's uncommon that you will need a custom container -- and if you do, it'll have to be a fixed-height element with `overflow-y: scroll` to work correctly.

These names `.fooReveal` and `.fooContainer` are things I used in the documentation, and don't need to be a part of your project.

### Just Keep It Simple

```html
<?php $this->addScript(T3_TEMPLATE_URL.'/js/scrollreveal.min.js'); ?>

<div class="myClass">Hello</div>

<script>
  window.sr = new ScrollReveal();
  sr.reveal('.myClass');
</script>
```

**Comment by PDX1337** [comment]
Hi could you help me via teamviewer ?

 

Would be very great 

 

Regards

PDX

Von: Julian Lloyd [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. September 2016 15:33
An: jlmakes/scrollreveal.js
Cc: PDX1337; Author
Betreff: Re: [jlmakes/scrollreveal.js] not work in Joomla ? (#295)

 

You call sr.reveal() on the elements with the .fooReveal class, but I don't see any; you declared a custom container with the class .fooContainer but I don't see it -- Plus, it's uncommon that you will need a custom container -- and if you do, it'll have to be a fixed-height element with overflow-y: scroll to work correctly.

These names .fooReveal and .fooContainer are things I used in the documentation, and don't need to be a part of your project.


Just Keep It Simple

<?php $this->addScript(T3_TEMPLATE_URL.'/js/scrollreveal.min.js'); ?>
 
<div class="myClass">Hello</div>
 
<script>
  window.sr = new ScrollReveal();
  sr.reveal('.myClass');
</script>

**Comment by PDX1337** [comment]
ok looks like it works now but it only animate 1 time i added reset to the class still not work

**Comment by PDX1337** [comment]
omg got it thanks
