### ISSUE TITLE
afteReaveal calling on page load not on scroll

### ISSUE THREAD

**Issue by pravinweb** [jlmakes/scrollreveal.js#300]
Hi Team

Thanks for this great plugin

I am using this on one page site. where I have around 25 elements over which I have added class .revealOnScroll and I am calling plugin over it.

I have also added afterReveal function with console log for debug. Issue is when page loads this function immediatly runs and show me 25 callbacks and not individaul callbacks as page scroll.

I also tried to add reset: true. When I scroll from bottom to top this works while vice versa it allready show all elements and not on scroll

my example code is as below

[example code](https://jsbin.com/kevozoboza/edit?html)

Many Thanks,
Pravin

**Comment by pravinweb** [comment]
I am sorry this is my mistake. surprisingly CMS removing `<!doctype html>`  which causing issue.

I am just wondering even how such small mistake can lead to not working of plugin can we add condition to check html is valid.

It's resolved now

many thanks
Pravin

**Comment by jlmakes** [comment]
That's definitely odd. Maybe there's a chance that without the HTML5 doctype, the `data-` attributes cause an issue?

**Comment by pravinweb** [comment]
Hi JilMakes,

I haven't added `data-` attribute. I initialise plugin in jQuery doc ready using class

for some other purpose on elements I had added `data-animation` tag No javascript written on this

Do you think this would have caused an issue

Thanks
Pravin
