### ISSUE TITLE
Feature request: grouping

### ISSUE THREAD

**Issue by jamie94bc** [jlmakes/scrollreveal.js#86]
A great addition would be able to group the animations.

For example, I have 2 elements (different sizes/positions) that I have set to animate but one of them has a delay. If the user scrolls the page, to a point where the viewport determines the first element is visible but not the second, when the user scrolls further down the page the second element will after after delay.

I realise that something similar to this is achievable with the viewport configuration value, but grouping would be a better solution :-)

**Comment by jlmakes** [comment]
Related to #187

**Comment by jlmakes** [comment]
### New In ScrollReveal v3.1
You can now pass a sequence interval (in milliseconds) to the `reveal()` method, making sequenced animations a breeze.
```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```
![sequencer](https://cloud.githubusercontent.com/assets/2044842/13556788/a7dda6c6-e3e2-11e5-93fa-d6a227cbb5dc.gif)

It was a beast to implement, but thanks for the request @jamie94bc :bow:

**Comment by jamie94bc** [comment]
Awesome! Great work @jlmakes :smiley:
